#!/usr/bin/env python3
# REBUILT 2026-09-22 from design recovered from session 2026-09-20
# transcript fragments. Original bytes lost. Sections marked [RECOVERED]
# match recovered text; sections marked [REBUILD-CHOICE] are new.
#
# INSTRUMENT-INDEX builder. One collect() pass, two renderings.
#
# This file is in SKIP_NAMES, so the comment block above is never read
# back as an instrument header.
#
# CC0. stdlib only. Parses under Python 3.9. ASCII.

import hashlib
import os
import subprocess
import sys
from datetime import datetime, timezone

# ---------------------------------------------------------------- [RECOVERED]

FIELDS = (
    "id", "name", "repo", "path", "input_shape", "catches",
    "load_bytes", "load_tok_est", "run_cost", "run_basis",
    "status", "gate", "built_against",
)

INPUT_SHAPES = (
    "CLAIM",         # a proposition with a truth value
    "FALSIFIER",     # a stated refutation condition
    "CATEGORY-SET",  # the bins themselves, not an item in them
    "NUMBER",        # a quantity, rate, or score
    "ABSENCE",       # a field reading zero / blank / unclear
    "CORPUS",        # a set of documents to be coded
    "DECISION",      # an option set presented for choice
    "DOCUMENT",      # whole-artifact structural checks
    "AGENT-OUTPUT",  # text produced by a model, audited as such
)

RUN_COSTS = ("TRIVIAL", "LINEAR", "QUADRATIC", "CORPUS", "EXTERNAL", "UNRATED")

RUN_BASES = ("measured", "counted-from-source", "author-estimate")

# [REBUILD-CHOICE] enum inferred from fixture values.
STATUSES = ("OBSERVED", "DERIVED", "PROPOSED", "UNRATED")

# gate: UNRUN is the default and is NOT the same as FAILED.
GATE_DEFAULT = "UNRUN"

UNRATED = "UNRATED"

EXTS = (".py", ".md", ".sh", ".txt")

SKIP_DIRS = (".git", "__pycache__", "node_modules", ".github")

SKIP_NAMES = (
    "README.md",
    "LICENSE",
    "index-overrides.json",
    "INSTRUMENT-INDEX.tsv",
    "build_index.py",
    # [REBUILD-CHOICE] also skip INSTRUMENT-INDEX.md
    "INSTRUMENT-INDEX.md",
)

AXIS_THRESHOLD = 0.70

AXIS_FALSIFIED = (
    "AXIS FALSIFIED: input_shape does not partition; fall back to "
    "output type (verdict/count/branch/refusal)"
)
AXIS_HOLDS = "axis holds at this build"
AXIS_UNRATED = "UNRATED: check not run"

NOT_SCANNED = "NOT-SCANNED"

ESTIMATE_NOTE = (
    "load_tok_est is bytes // 4, an ESTIMATE. No tokenizer in the loop. "
    "An estimate labeled as an estimate is usable; an estimate wearing a "
    "number is not."
)

GENERATED_NOTE = "GENERATED by build_index.py. Do not hand-edit."

# [REBUILD-CHOICE] the original six lines were not recovered. Replaceable
# when the original turns up.
COVERAGE_DECLARATION = (
    "instruments consulted:",
    "instruments in scope but not run:",
    "unrated files in scope:",
    "axis-check verdict at build:",
    "built_against states:",
    "not checked:",
)

# [REBUILD-CHOICE] header keys, exact uppercase, one comment character
# ('#') for all four extensions so one parser reads .py .md .sh .txt.
HEADER_KEYS = {
    "INSTRUMENT": "name",
    "INPUT": "input_shape",
    "CATCHES": "catches",
    "RUN-COST": "run_cost",
    "STATUS": "status",
    "GATE": "gate",
}


# ---------------------------------------------------------------------------
# values


def scrub(value):
    """[RECOVERED] tabs/newlines in values -> spaces."""
    out = []
    for ch in str(value):
        out.append(" " if ch in "\t\r\n" else ch)
    return "".join(out).strip()


def parse_header(text):
    """[RECOVERED] in-file header, parsed from the leading comment block.

    Stops at the first non-comment line. [REBUILD-CHOICE] a blank line is
    not a comment line, so a blank line terminates the block.
    """
    found = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("#"):
            break
        body = stripped.lstrip("#").strip()
        if ":" not in body:
            continue
        key, _, value = body.partition(":")
        key = key.strip()
        if key in HEADER_KEYS:
            found[HEADER_KEYS[key]] = scrub(value)
    return found


def split_run_cost(raw):
    """RUN-COST: TRIVIAL (author-estimate) -> ('TRIVIAL', 'author-estimate').

    The value in parentheses is run_basis. [REBUILD-CHOICE] the
    parenthetical is optional at parse time; a run_cost other than UNRATED
    with an empty run_basis is a flag, not a parse failure.
    """
    raw = scrub(raw)
    cost, basis = raw, ""
    if raw.endswith(")") and "(" in raw:
        head, _, tail = raw.rpartition("(")
        cost = head.strip()
        basis = tail[:-1].strip()
    return cost, basis


def shape_list(value):
    """input_shape is multi-valued, pipe-separated."""
    if value == UNRATED:
        return []
    return [p.strip() for p in value.split("|") if p.strip()]


# ---------------------------------------------------------------------------
# overrides


def read_overrides(root):
    """[RECOVERED] fallback: index-overrides.json keyed by relative path."""
    import json
    path = os.path.join(root, "index-overrides.json")
    if not os.path.isfile(path):
        return {}
    with open(path, "r") as fh:
        raw = json.load(fh)
    out = {}
    for key, rec in raw.items():
        if not isinstance(rec, dict):
            continue
        out[key.replace(os.sep, "/")] = {
            k: scrub(v) for k, v in rec.items() if k in FIELDS
        }
    return out


# ---------------------------------------------------------------------------
# built_against


def fingerprint(root, relpaths):
    """[REBUILD-CHOICE] sha256 over sorted 'relpath\\0mtime_ns' lines."""
    h = hashlib.sha256()
    for rel in sorted(relpaths):
        full = os.path.join(root, rel)
        try:
            mtime = os.stat(full).st_mtime_ns
        except OSError:
            mtime = 0
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(str(mtime).encode("ascii"))
        h.update(b"\n")
    return "nogit-" + h.hexdigest()[:10]


def built_against(root, relpaths):
    """[RECOVERED] short git hash, else nogit-<...>. Never guess."""
    try:
        out = subprocess.run(
            ["git", "-C", root, "rev-parse", "--short", "HEAD"],
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
    except (OSError, ValueError):
        return fingerprint(root, relpaths)
    if out.returncode != 0:
        return fingerprint(root, relpaths)
    short = out.stdout.decode("ascii", "replace").strip()
    if not short:
        return fingerprint(root, relpaths)
    return short


# ---------------------------------------------------------------------------
# walk


def walk_repo(root):
    """[RECOVERED] EXTS, SKIP_DIRS, SKIP_NAMES. Never drop a file."""
    rels = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            if name in SKIP_NAMES:
                continue
            if not name.endswith(EXTS):
                continue
            full = os.path.join(dirpath, name)
            rels.append(os.path.relpath(full, root).replace(os.sep, "/"))
    return rels


# ---------------------------------------------------------------------------
# flags -- [REBUILD-CHOICE] whole section


def row_flags(row):
    """Flags never alter the row value."""
    out = []
    for token in shape_list(row["input_shape"]):
        if token not in INPUT_SHAPES:
            out.append((row["id"], "input_shape",
                        "value outside the enum: %s" % token))
    if row["run_cost"] not in RUN_COSTS:
        out.append((row["id"], "run_cost",
                    "value outside the enum: %s (kept, not normalized)"
                    % row["run_cost"]))
    if row["run_cost"] != UNRATED and not row["run_basis"]:
        out.append((row["id"], "run_basis",
                    "run_cost is %s and run_basis is empty" % row["run_cost"]))
    if row["run_basis"] and row["run_basis"] not in RUN_BASES:
        out.append((row["id"], "run_basis",
                    "value outside the enum: %s" % row["run_basis"]))
    return out


# ---------------------------------------------------------------------------
# collect -- one pass, both writers read these rows


def blank_row():
    row = dict.fromkeys(FIELDS, UNRATED)
    row["run_basis"] = ""
    row["gate"] = GATE_DEFAULT
    return row


def collect(repo_args):
    """[RECOVERED] collect() once; neither rendering derives from the other."""
    rows = []
    repos = []
    flags = []
    for label in repo_args:
        if not os.path.isdir(label):
            # [RECOVERED] path passed but missing -> NOT-SCANNED, distinct
            # from scanned with zero rated rows.
            # [REBUILD-CHOICE] a path that exists and is not a directory is
            # NOT-SCANNED too.
            repos.append({"label": label, "state": NOT_SCANNED,
                          "built_against": NOT_SCANNED, "rows": []})
            continue
        rels = walk_repo(label)
        stamp = built_against(label, rels)
        overrides = read_overrides(label)
        repo_rows = []
        for rel in rels:
            full = os.path.join(label, rel)
            with open(full, "rb") as fh:
                raw = fh.read()
            text = raw.decode("utf-8", "replace")
            row = blank_row()
            # [REBUILD-CHOICE] id is '<repo label>:<relative path>'.
            row["id"] = "%s:%s" % (label, rel)
            # [REBUILD-CHOICE] repo is the path exactly as passed.
            row["repo"] = label
            row["path"] = rel
            row["load_bytes"] = str(len(raw))
            row["load_tok_est"] = str(len(raw) // 4)
            row["built_against"] = stamp
            over = overrides.get(rel, {})
            head = parse_header(text)
            # [RECOVERED] the in-file header wins over the override.
            for key in ("name", "input_shape", "catches", "status", "gate"):
                if key in head:
                    row[key] = head[key]
                elif key in over:
                    row[key] = over[key]
            if "run_cost" in head:
                cost, basis = split_run_cost(head["run_cost"])
                row["run_cost"] = cost
                row["run_basis"] = basis
            else:
                if "run_cost" in over:
                    row["run_cost"] = over["run_cost"]
                if "run_basis" in over:
                    row["run_basis"] = over["run_basis"]
            flags.extend(row_flags(row))
            repo_rows.append(row)
        rows.extend(repo_rows)
        repos.append({"label": label, "state": "SCANNED",
                      "built_against": stamp, "rows": repo_rows})
    return rows, repos, flags


# ---------------------------------------------------------------------------
# axis check


def axis_check(rows):
    """[RECOVERED] pre-stated falsifier, run on every build."""
    rated = [r for r in rows if r["input_shape"] != UNRATED]
    if not rated:
        return AXIS_UNRATED, 0, 0, None
    claim_only = [r for r in rated if shape_list(r["input_shape"]) == ["CLAIM"]]
    frac = float(len(claim_only)) / float(len(rated))
    verdict = AXIS_FALSIFIED if frac > AXIS_THRESHOLD else AXIS_HOLDS
    return verdict, len(rated), len(claim_only), frac


def claim_only_fraction(rows):
    """Fraction of rated rows whose ONLY shape is CLAIM. None when no rated
    rows: an empty rated set is not a fraction of zero."""
    return axis_check(rows)[3]


def unrated_rows(rows):
    return [r for r in rows if r["input_shape"] == UNRATED]


def total_tok_est(rows):
    return sum(int(r["load_tok_est"]) for r in rows)


# ---------------------------------------------------------------------------
# renderings


def _axis_line(rows):
    verdict, rated, claim_only, frac = axis_check(rows)
    if frac is None:
        return "%s (rated rows: 0)" % verdict
    return "%s (claim-only %d / rated %d = %.3f, threshold %.2f)" % (
        verdict, claim_only, rated, frac, AXIS_THRESHOLD)


def write_tsv(path, rows, repos, flags, stamp):
    """Agent view."""
    out = []
    out.append("# %s" % GENERATED_NOTE)
    out.append("# stamp: %s" % stamp)
    for rec in repos:
        out.append("# repo: %s  state: %s  rows: %d  built_against: %s" % (
            rec["label"], rec["state"], len(rec["rows"]), rec["built_against"]))
    out.append("# rows: %d" % len(rows))
    out.append("# estimate: %s" % ESTIMATE_NOTE)
    out.append("# axis-check: %s" % _axis_line(rows))
    out.append("# unrated: %d (to-do, located, not hidden)"
               % len(unrated_rows(rows)))
    out.append("# total_load_tok_est: %d" % total_tok_est(rows))
    out.append("# flags: %d" % len(flags))
    out.append("\t".join(FIELDS))
    for row in rows:
        out.append("\t".join(scrub(row[f]) for f in FIELDS))
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")


def _repo_load(rec):
    return sum(int(r["load_tok_est"]) for r in rec["rows"])


def write_md(path, rows, repos, flags, stamp):
    """Human view."""
    out = []
    out.append("# INSTRUMENT-INDEX")
    out.append("")
    out.append(GENERATED_NOTE)
    out.append("")
    out.append("Stamp: %s" % stamp)
    out.append("")
    out.append("## Build state")
    out.append("")
    out.append("| repo | state | rows |")
    out.append("| --- | --- | --- |")
    for rec in repos:
        out.append("| %s | %s | %d |" % (rec["label"], rec["state"],
                                         len(rec["rows"])))
    out.append("")
    out.append("## Instruments")
    out.append("")
    # [REBUILD-CHOICE] repos sorted by load cost descending; NOT-SCANNED
    # repos sort last, since they have no load to rank.
    ordered = sorted(
        repos,
        key=lambda rec: (rec["state"] == NOT_SCANNED, -_repo_load(rec),
                         rec["label"]),
    )
    for rec in ordered:
        out.append("### %s" % rec["label"])
        out.append("")
        if rec["state"] == NOT_SCANNED:
            out.append("Unknown contents, not an empty repo.")
            out.append("")
            continue
        rated = [r for r in rec["rows"] if r["input_shape"] != UNRATED]
        if not rated:
            out.append("Scanned, no rated instruments found (%d file(s) "
                       "unrated)." % len(rec["rows"]))
            out.append("")
            continue
        out.append("| catches | id | name | path | input_shape | run_cost | "
                   "run_basis | status | gate | load_tok_est |")
        out.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- "
                   "| --- |")
        for row in rated:
            out.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                row["catches"], row["id"], row["name"], row["path"],
                row["input_shape"], row["run_cost"],
                row["run_basis"] or "(empty)", row["status"], row["gate"],
                row["load_tok_est"]))
        out.append("")
    out.append("## Axis check")
    out.append("")
    out.append(_axis_line(rows))
    out.append("")
    out.append("The threshold is %.2f: a rated set more than %.0f%% of which "
               "carries CLAIM alone does not partition." % (
                   AXIS_THRESHOLD, AXIS_THRESHOLD * 100))
    out.append("")
    out.append("## Validity flags")
    out.append("")
    if not flags:
        out.append("None at this build.")
    else:
        out.append("| row | field | note |")
        out.append("| --- | --- | --- |")
        for rid, field, note in flags:
            out.append("| %s | %s | %s |" % (rid, field, note))
    out.append("")
    out.append("Flags never alter the row value.")
    out.append("")
    out.append("## Unrated set")
    out.append("")
    out.append("To-do, located, not hidden. %d row(s)."
               % len(unrated_rows(rows)))
    out.append("")
    for row in unrated_rows(rows):
        out.append("- %s" % row["id"])
    out.append("")
    out.append("## Load")
    out.append("")
    out.append("total_load_tok_est: %d" % total_tok_est(rows))
    out.append("")
    out.append(ESTIMATE_NOTE)
    out.append("")
    out.append("## Coverage declaration")
    out.append("")
    out.append("[REBUILD-CHOICE] The original six lines were not recovered. "
               "Replaceable when the original turns up.")
    out.append("")
    for line in COVERAGE_DECLARATION:
        out.append("- %s" % line)
    out.append("")
    out.append("built_against states: %s" % ", ".join(
        "%s=%s" % (rec["label"], rec["built_against"]) for rec in repos))
    out.append("")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")


# ---------------------------------------------------------------------------
# cli


USAGE = "usage: build_index.py --tsv OUT.tsv --md OUT.md repo1 repo2 ..."


def main(argv):
    if "--selftest" in argv:
        sys.stderr.write(
            "build_index.py has no --selftest. Run:\n"
            "  python3 instrument-index/tests/test_build_index.py\n")
        return 2
    tsv = md = None
    repos = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--tsv" and i + 1 < len(argv):
            tsv = argv[i + 1]
            i += 2
        elif arg == "--md" and i + 1 < len(argv):
            md = argv[i + 1]
            i += 2
        else:
            repos.append(arg)
            i += 1
    if tsv is None or md is None or not repos:
        sys.stderr.write(USAGE + "\n")
        return 2
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rows, repo_states, flags = collect(repos)
    write_tsv(tsv, rows, repo_states, flags, stamp)
    write_md(md, rows, repo_states, flags, stamp)
    for rid, field, note in flags:
        sys.stderr.write("FLAG %s %s: %s\n" % (rid, field, note))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
