"""MSIAF proxy catalog — every cataloged proxy as a structured candidate.

Sourced from msiaf-framework/proxies/proxy-catalog.md. Each entry carries the
claimed mapping and the lab's prior grades before investigation."""
CATALOG = [
    # rail
    {"id": "rail-unplanned-maintenance", "mode": "rail",
     "target": "Infrastructure degradation", "observable": "Unplanned maintenance request frequency",
     "mapping": "Positive: degradation forces reactive work orders",
     "chain": [("degradation->failures", 0.85, "estimated"), ("failures->work orders", 0.9, "measured")]},
    {"id": "rail-speed-restrictions", "mode": "rail",
     "target": "Localized track defects", "observable": "Speed restriction frequency per segment",
     "mapping": "Positive: defects trigger slow orders",
     "chain": [("defect->inspection finding", 0.8, "estimated"), ("finding->restriction", 0.9, "measured")]},
    # ports
    {"id": "port-dwell-time", "mode": "port",
     "target": "Terminal inefficiency/congestion", "observable": "Drayage dwell time",
     "mapping": "Positive: congestion lengthens queues",
     "chain": [("congestion->dwell", 0.85, "measured"), ("dwell->risk pressure", 0.65, "estimated"), ("capture", 0.95, "measured")]},
    {"id": "port-cargo-damage", "mode": "port",
     "target": "Poor material-handling protocols", "observable": "Cargo damage claim rate",
     "mapping": "Positive: bad handling produces damage",
     "chain": [("protocol->handling quality", 0.7, "estimated"), ("quality->damage", 0.8, "estimated"), ("claims capture", 0.85, "measured")]},
    # waterways
    {"id": "river-water-level", "mode": "waterway",
     "target": "Navigation hazard", "observable": "Water level fluctuation",
     "mapping": "Direct physical: depth determines draft clearance",
     "chain": [("level->clearance", 0.95, "measured"), ("gauge capture", 0.98, "measured")]},
    {"id": "river-draft-limits", "mode": "waterway",
     "target": "Reduced cargo capacity", "observable": "Unexpected draft limit issuance",
     "mapping": "Direct regulatory signal of depth constraint",
     "chain": [("depth->limit", 0.92, "measured"), ("limit->capacity", 0.95, "measured")]},
    # light duty
    {"id": "ldv-service-trips", "mode": "light_duty",
     "target": "Supply chain pressure", "observable": "Delivery/service trip frequency",
     "mapping": "Positive: demand pressure raises trip counts",
     "chain": [("pressure->dispatch volume", 0.6, "estimated"), ("volume->trips", 0.85, "measured")]},
    {"id": "ldv-roadside-calls", "mode": "light_duty",
     "target": "Deferred maintenance / heavy use", "observable": "Emergency roadside-assistance calls",
     "mapping": "Positive: degraded vehicles fail more",
     "chain": [("deferral->failure", 0.7, "estimated"), ("failure->call", 0.8, "estimated"), ("capture", 0.9, "measured")]},
    {"id": "ldv-congestion-time", "mode": "light_duty",
     "target": "Local infrastructure strain", "observable": "Time-in-congestion for service vehicles",
     "mapping": "Positive: strain manifests as delay",
     "chain": [("strain->delay", 0.75, "estimated"), ("GPS capture", 0.95, "measured")]},
    # freight/intermodal
    {"id": "freight-terminal-throughput", "mode": "intermodal",
     "target": "System capacity pressure", "observable": "Daily terminal throughput",
     "mapping": "Positive: pressure saturates terminals",
     "chain": [("pressure->volume", 0.75, "estimated"), ("TOS capture", 0.95, "measured")]},
    {"id": "freight-container-dwell", "mode": "intermodal",
     "target": "Transfer friction", "observable": "Average container dwell time",
     "mapping": "Positive: friction holds containers longer",
     "chain": [("friction->dwell", 0.8, "estimated"), ("capture", 0.95, "measured")]},
    {"id": "freight-corridor-volume", "mode": "corridor",
     "target": "Physical pavement/bridge load", "observable": "Freight volume through corridor",
     "mapping": "Fourth-power damage law on measured axle spectra",
     "chain": [("volume->axle spectrum", 0.9, "measured"), ("spectrum->fatigue", 0.9, "measured")]},
    # behavioral / aerial
    {"id": "behavior-venue-congestion", "mode": "behavioral",
     "target": "Experiential vs resource-acquisition trip mix", "observable": "Congestion patterns around venues vs retail",
     "mapping": "Differential timing signatures distinguish trip purpose",
     "chain": [("purpose->timing", 0.55, "assumed"), ("mobile-data capture", 0.7, "estimated")]},
    {"id": "drone-corridor-density", "mode": "aerial",
     "target": "Airspace-conflict risk", "observable": "Corridor density near landing zones",
     "mapping": "Positive: density raises conflict probability",
     "chain": [("density->conflict", 0.6, "assumed"), ("UTM capture", 0.8, "estimated")]},
    # warehouse (from MSIAF warehouse model)
    {"id": "wh-temp-turnover", "mode": "warehouse",
     "target": "Hazardous conditions / algorithmic over-pacing", "observable": "Temp staff turnover rate",
     "mapping": "Positive: bad conditions drive quits",
     "chain": [("hazard->quit intent", 0.55, "assumed"), ("intent->turnover", 0.6, "estimated"), ("HR capture", 0.9, "measured")]},
    {"id": "wh-late-fee-waivers", "mode": "port",
     "target": "Systemic port congestion", "observable": "Late-fee waiver frequency to drayage drivers",
     "mapping": "Positive: congestion forces waivers",
     "chain": [("congestion->lateness", 0.8, "estimated"), ("lateness->waiver", 0.7, "estimated"), ("ledger capture", 0.95, "measured")]},
]
