#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
"""
credential_channel -- WO-10, five instruments bundled because they were
observed on one plant floor, built to the order and run on CONSTRUCTED
data. They are separable: different measurands, different failure modes,
each runs alone. No plant, worker, record or review is read; every world
is generated by a declared model and nothing here is a statement about
any person or workplace.

  I-1  the format gate         written route vs demonstrate route, against
                               later performance; plus the methodology-
                               objection coding (engage vs cite prior usage)
  I-2  authority-competence     the routing-cost join: cost per fault event
       inversion                attributable to ROUTING, not to the fault
  I-3  manufactured confidence  confidence-accuracy gap against years of
                               exposure to the gate, in the DOWNWARD direction
  I-4  introversion             inventory score against cumulative exposure:
                               trait or produced by the gate
  I-5  attribution at the       reported credit vs ground truth; error rate
       wrong node               by hierarchy level

spearman is imported from readout-count and ols from sim-span, not copied.

Python 3.9, ASCII only, stdlib only. Refuses --selftest; the checks live
in test_credential.py.
"""

from __future__ import annotations

import os
import random
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "readout-count"))
sys.path.insert(0, os.path.join(_ROOT, "sim-span"))
from readout_count import spearman     # noqa: E402  (imported, not copied)
from three_column import ols           # noqa: E402  (imported, not copied)

STATUS = ("OBSERVED", "DERIVED", "PROPOSED", "CONSTRUCTED", "CARRIED")

CHOICES = {
    1: "I-1 ranks each route's selection score against later performance "
       "with Spearman rho; the gate is uncorrelated or inverse iff route A "
       "(written) rho is at or below zero while route B (demonstrate) is "
       "positive",
    2: "I-1's methodology-objection coding is ENGAGE vs CITE_PRIOR_USAGE "
       "from a declared response field; the ratio is reported by speaker "
       "status, not adjudicated",
    3: "I-2 attributes to ROUTING the external cost plus the downtime cost "
       "of any event whose actual resolver differs from the authorised one "
       "AND whose resolution content is cheap; a procedure change is NOT "
       "modelled as the cause",
    4: "I-2's downtime cost is downtime hours times a stipulated 150/hour",
    5: "I-3 and I-4 regress the gap (or the inventory score) on years of "
       "exposure with ols; the sign of the exposure coefficient is the "
       "readout, the downward direction being negative",
    6: "I-5 reports attribution error rate by hierarchy level from ground "
       "truth against reported credit; a level with no events is None",
}

HOURLY = 150.0                                              # [CHOICE 4]


class Refused(ValueError):
    """Raised at intake. A refused record never reaches a readout."""


def absent(v):
    return v is None or v == "" or v == "UNDECLARED"


# ===================================================================== I-1

def i1_route_correlation(candidates):                       # [CHOICE 1]
    """candidates: {route_a_score, route_b_score, performance}. Two rank
    correlations against performance. The claim under test: route A is
    uncorrelated or inverse while route B is positive."""
    a = [c["route_a_score"] for c in candidates]
    b = [c["route_b_score"] for c in candidates]
    perf = [c["performance"] for c in candidates]
    ra = spearman(a, perf)
    rb = spearman(b, perf)
    if ra is None or rb is None:
        return {"rho_a": ra, "rho_b": rb,
                "verdict": "NOT_EVALUABLE (a side is constant or too few)"}
    if ra <= 0 < rb:
        v = "the gate is uncorrelated or inverse; demonstrate outperforms"
    elif ra > 0 and rb > 0:
        v = "both routes track performance; the gate is not the problem here"
    else:
        v = "mixed; the claim is not supported by this pool"
    return {"rho_a": ra, "rho_b": rb, "verdict": v}


def i1_objection_coding(responses):                         # [CHOICE 2]
    """responses to a methodology objection: {status, kind} with kind in
    {'engage', 'cite_prior_usage'}. Ratio of engagement by speaker status.
    Prior use is not construct validity; the coding reports which move was
    made, it does not adjudicate the objection."""
    by = {}
    for r in responses:
        if r["kind"] not in ("engage", "cite_prior_usage"):
            raise Refused("i1_objection_coding: kind must be engage or cite_prior_usage")
        d = by.setdefault(r["status"], {"engage": 0, "cite_prior_usage": 0})
        d[r["kind"]] += 1
    out = {}
    for status, d in by.items():
        n = d["engage"] + d["cite_prior_usage"]
        out[status] = {"engage_share": d["engage"] / n, "n": n}
    return out


# ===================================================================== I-2

def i2_routing_cost(events):                                # [CHOICE 3,4]
    """events: {authorised, actual, resolution_cheap (bool), downtime_hours,
    external_cost}. Cost attributable to ROUTING (not the fault): the
    external cost plus downtime cost of any event resolved by someone other
    than the authorised responder with a cheap resolution.

    The order's mechanism note: the block is overshadowing/ripple avoidance,
    NOT procedure. Procedure makes it legible; a procedure change is not
    modelled as the cause, so this measures the routing gap directly.
    """
    total, per = 0.0, []
    for e in events:
        if absent(e.get("authorised")) or absent(e.get("actual")):
            raise Refused("i2_routing_cost: authorised and actual required")
        routed = (e["actual"] != e["authorised"]) and e.get("resolution_cheap", False)
        cost = (e.get("external_cost", 0.0) + e.get("downtime_hours", 0.0) * HOURLY) if routed else 0.0
        total += cost
        per.append({"routed": routed, "cost": cost})
    return {"n": len(events), "routing_cost_total": total,
            "n_routed": sum(1 for p in per if p["routed"]),
            "per_event": per,
            "mean_per_routed": None if not any(p["routed"] for p in per)
            else total / sum(1 for p in per if p["routed"])}


def routing_cost(external, downtime_hours):
    """The per-event routing-attributable cost of a routed event:
    external + downtime_hours * HOURLY. Registered in
    tools/known_answer.py."""
    return external + downtime_hours * HOURLY


# ===================================================================== I-3

def i3_gap_vs_exposure(rows):                               # [CHOICE 5]
    """rows: {confidence, hit_rate, exposure_years}. Regress the
    confidence-accuracy gap (confidence - hit_rate) on exposure. The order's
    prediction: the gap widens DOWNWARD with exposure, so the coefficient is
    negative -- confidence falls below hit rate as exposure grows,
    independent of accuracy."""
    y = [r["confidence"] - r["hit_rate"] for r in rows]
    x = [[r["exposure_years"] for r in rows]]
    beta, r2 = ols(y, x)
    if beta is None:
        return {"exposure_coef": None, "verdict": "NOT_EVALUABLE (singular)"}
    coef = beta[1]
    return {"exposure_coef": coef, "r_squared": r2,
            "verdict": ("gap widens downward with exposure (coef < 0)" if coef < 0
                        else "gap widens upward with exposure (coef > 0)" if coef > 0
                        else "no exposure trend")}


# ===================================================================== I-4

def i4_inventory_vs_exposure(rows):                         # [CHOICE 5]
    """rows: {inventory_score, exposure_years}. If the introversion score
    tracks exposure, the inventory is partly measuring history, not
    disposition. Same structure as I-3."""
    y = [r["inventory_score"] for r in rows]
    x = [[r["exposure_years"] for r in rows]]
    beta, r2 = ols(y, x)
    if beta is None:
        return {"exposure_coef": None, "verdict": "NOT_EVALUABLE (singular)"}
    coef = beta[1]
    return {"exposure_coef": coef, "r_squared": r2,
            "verdict": ("the inventory is partly measuring history, not "
                        "disposition (score tracks exposure)" if abs(coef) > 1e-6
                        else "no exposure trend; the score is not exposure-loaded")}


# ===================================================================== I-5

def i5_attribution_error(events):                           # [CHOICE 6]
    """events: {resolver_level, credited_level}. Attribution error rate by
    the level CREDITED, and its direction. Ground truth is the resolver;
    the credited party is who the record names."""
    by = {}
    for e in events:
        rl, cl = e["resolver_level"], e["credited_level"]
        d = by.setdefault(cl, {"events": 0, "errors": 0})
        d["events"] += 1
        if rl != cl:
            d["errors"] += 1
    out = {}
    for level, d in by.items():
        out[level] = {"events": d["events"],
                      "error_rate": None if d["events"] == 0 else d["errors"] / d["events"]}
    # direction: does credit flow up? share of errors where credited > resolver
    up = sum(1 for e in events if e["credited_level"] > e["resolver_level"])
    err = sum(1 for e in events if e["credited_level"] != e["resolver_level"])
    return {"by_credited_level": out,
            "upward_share": None if err == 0 else up / err,
            "reads": "a downstream statistic on these reports measures "
                     "REPORTING POSITION, not competence"}


# =============================================== constructed worlds (declared)

def i1_candidates(seed=1, n=40):
    """route B (demonstrate) tracks performance; route A (written) does
    not -- the order's claim as a declared model, so I-1 is a known-answer
    run on the correlation."""
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        perf = rng.gauss(0, 1)
        out.append({"performance": perf,
                    "route_b_score": perf + rng.gauss(0, 0.3),
                    # the order's stronger claim: the written gate is
                    # inversely correlated with the ability selected for
                    "route_a_score": -0.4 * perf + rng.gauss(0, 0.7)})
    return out


def i1_objections():
    return ([{"status": "senior", "kind": "cite_prior_usage"}] * 7 +
            [{"status": "senior", "kind": "engage"}] * 3 +
            [{"status": "junior", "kind": "engage"}] * 8 +
            [{"status": "junior", "kind": "cite_prior_usage"}] * 2)


def i2_events():
    """CONSTRUCTED: the forklift-fuse and the four-mechanics events plus
    routine ones; the two field cases are resolved off-authorisation and
    cheaply."""
    return [
        {"authorised": "certified mechanic", "actual": "operator",
         "resolution_cheap": True, "downtime_hours": 2.0, "external_cost": 0.0},
        {"authorised": "certified mechanic", "actual": "operator",
         "resolution_cheap": True, "downtime_hours": 6.0, "external_cost": 0.0},
        {"authorised": "certified mechanic", "actual": "certified mechanic",
         "resolution_cheap": False, "downtime_hours": 1.0, "external_cost": 250.0},
        {"authorised": "operator", "actual": "operator",
         "resolution_cheap": True, "downtime_hours": 0.5, "external_cost": 0.0},
    ]


def i3_rows(seed=2, n=60):
    """gap falls with exposure (downward), independent of hit rate -- the
    order's prediction as a declared model."""
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        exp = rng.uniform(0, 25)
        hit = rng.uniform(0.4, 0.8)
        conf = hit + 0.2 - 0.02 * exp + rng.gauss(0, 0.03)
        out.append({"confidence": conf, "hit_rate": hit, "exposure_years": exp})
    return out


def i4_rows(seed=4, n=60):
    """inventory score tracks exposure -- the produced-quiet model."""
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        exp = rng.uniform(0, 25)
        out.append({"inventory_score": 3.0 + 0.05 * exp + rng.gauss(0, 0.2),
                    "exposure_years": exp})
    return out


def i5_events(seed=6, n=50):
    """credit flows up: the resolver is often a lower level than the
    credited party."""
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        resolver = rng.choice([1, 1, 1, 2, 2, 3])
        credited = resolver + (rng.choice([1, 2]) if rng.random() < 0.6 else 0)
        out.append({"resolver_level": resolver, "credited_level": credited})
    return out


CARRIED = {
    "combine_cognitive_architecture":
        "JinnZ2/Combine-Cognitive-Architecture- (CC0): credentials != "
        "competence; L1 extraction with no self-reports, L3 matching with "
        "no resumes. I-1 and I-3 are instrumented there, predating this "
        "write-up. NOT in this tree; parts of that README are another "
        "model's overlay and are not attributed here.",
    "specialisation_assumption":
        "OBSERVED: range is read as requiring specialisation (perfect pitch "
        "precludes the other thing). Position: hearing pitch and reading a "
        "machine are the same operation -- fine-grained deviation detection "
        "against an expected pattern. NOT YET RUNNABLE: needs a measurand "
        "before it can be designed. Filed so it is not lost.",
}


# ------------------------------------------------------------------ render

def refuse_selftest(name):
    sys.stderr.write("%s carries no selftest; run python3 test_credential.py\n"
                     % name)
    return 2


def render():
    out = ["WO-10  CREDENTIAL CHANNEL, five instruments   (data "
           "CONSTRUCTED, PROPOSED; no plant read)", "-" * 72]
    r = i1_route_correlation(i1_candidates())
    out.append("I-1  format gate   [CHOICE 1]")
    out.append("    route A (written) rho %.3f  route B (demonstrate) rho "
               "%.3f -> %s" % (r["rho_a"], r["rho_b"], r["verdict"]))
    oc = i1_objection_coding(i1_objections())
    for status in sorted(oc):
        out.append("    objection: %-7s engage share %.3f (n %d)   [CHOICE 2]"
                   % (status, oc[status]["engage_share"], oc[status]["n"]))
    out.append("")
    i2 = i2_routing_cost(i2_events())
    out.append("I-2  routing-cost join   [CHOICE 3,4]")
    out.append("    %d events, %d routed off-authorisation; cost "
               "attributable to routing %.0f (mean per routed %.0f)"
               % (i2["n"], i2["n_routed"], i2["routing_cost_total"],
                  i2["mean_per_routed"]))
    out.append("")
    i3 = i3_gap_vs_exposure(i3_rows())
    out.append("I-3  confidence-accuracy gap vs exposure   [CHOICE 5]")
    out.append("    exposure coef %+.4f  r2 %.3f -> %s"
               % (i3["exposure_coef"], i3["r_squared"], i3["verdict"]))
    out.append("")
    i4 = i4_inventory_vs_exposure(i4_rows())
    out.append("I-4  inventory score vs exposure   [CHOICE 5]")
    out.append("    exposure coef %+.4f  r2 %.3f -> %s"
               % (i4["exposure_coef"], i4["r_squared"], i4["verdict"]))
    out.append("")
    i5 = i5_attribution_error(i5_events())
    out.append("I-5  attribution mismatch by credited level   [CHOICE 6]")
    for lvl in sorted(i5["by_credited_level"]):
        d = i5["by_credited_level"][lvl]
        out.append("    level %d  mismatch rate %s (n %d)"
                   % (lvl, "None" if d["error_rate"] is None else "%.3f" % d["error_rate"],
                      d["events"]))
    out.append("    upward share of mismatches %.3f -- %s"
               % (i5["upward_share"], i5["reads"]))
    out.append("")
    out.append("carried: Combine-Cognitive-Architecture (not in this tree, "
               "overlay not attributed); the specialisation assumption "
               "(NOT YET RUNNABLE, requires a measurand)")
    return "\n".join(out) + "\n"


def main(argv):
    if "--selftest" in argv:
        return refuse_selftest("credential_channel.py")
    if "--choices" in argv:
        for k in sorted(CHOICES):
            sys.stdout.write("[CHOICE %d] %s\n" % (k, CHOICES[k]))
        return 0
    sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
