"""
aperture_alias_demo.py — the S(k) control SIM-A never ran.

CC0-1.0. Standard library only. Deterministic.

WHY THIS FILE EXISTS
--------------------
The back-trace of this drop (../reasoning-gate/SIM_STACK_BACKTRACE.md)
calls SIM-A an artifact and names the control that would settle it in one
run: feed a periodic point set — already in hand from SIM-B — through the
same S(k) code. If the lattice also shows only k=0, grid aliasing is
confirmed.

That exact control cannot be run here: the drop shipped results, not
generators, so there is no "same S(k) code" to feed anything through.
What CAN be done is test the mechanism directly, with declared parameters
and point sets whose spectra are known analytically. That is what this
file does.

Two claims are on the table, and they are separable:

  A1  the k-grid is too coarse to land on Bragg peaks, so the peaks are
      missed and only k=0 — which is guaranteed to land — survives

  A2  the reported "diffuse floor" of 2.08 for Ammann-Beenker cannot be
      the tiling's structure factor, because a quasiperiodic set has a
      PURE POINT spectrum whose between-peak floor is near zero. AB
      reading 2.08 while the cascade reads 0.96 is backwards: the
      quasicrystal should sit BELOW the random set, not 2x above it

Both are tested below in one dimension, where the Fibonacci chain is the
standard analogue of an Ammann-Beenker tiling — cut-and-project,
quasiperiodic, pure point spectrum — and where the structure factor of
each probe is known in closed form. The aliasing arithmetic (grid spacing
vs peak width) is identical in any dimension.

WHAT THIS IS NOT
----------------
Not a reproduction of SIM-A. Not a 2D Ammann-Beenker tiling. It cannot
tell you what the drop's code actually did. It tests whether the proposed
mechanism produces the reported signature, which is the part that can be
settled without the generators.
"""

from __future__ import annotations

import math
import random

TAU = (1.0 + 5.0 ** 0.5) / 2.0

N_POINTS = 1000
DK = 0.39          # k-grid spacing, from the back-trace's reading of SIM-A
N_K = 400
SEED = 20260815


# ---------------------------------------------------------------------------
# probes
# ---------------------------------------------------------------------------

def fibonacci_chain(n: int) -> list[float]:
    """
    Quasiperiodic. Long/short intervals in golden ratio, generated by the
    substitution L -> LS, S -> L. Pure point diffraction spectrum — the 1D
    analogue of an Ammann-Beenker tiling.
    """
    seq = "L"
    while len(seq) < n:
        seq = "".join("LS" if c == "L" else "L" for c in seq)
    pos, x = [], 0.0
    for c in seq[:n]:
        pos.append(x)
        x += TAU if c == "L" else 1.0
    return pos


def lattice(n: int, spacing: float) -> list[float]:
    """Periodic. Bragg peaks at k = 2*pi*m/spacing, nothing between them."""
    return [i * spacing for i in range(n)]


def poisson(n: int, length: float, rng: random.Random) -> list[float]:
    """Uncorrelated. S(k) -> 1 for all k != 0. The reference floor."""
    return sorted(rng.random() * length for _ in range(n))


# ---------------------------------------------------------------------------
# structure factor
# ---------------------------------------------------------------------------

def structure_factor(k: float, pts: list[float]) -> float:
    """S(k) = |sum_j exp(i k x_j)|^2 / N. Direct sum, no binning."""
    c = s = 0.0
    for x in pts:
        c += math.cos(k * x)
        s += math.sin(k * x)
    return (c * c + s * s) / len(pts)


def sampled_profile(pts: list[float], dk: float, n_k: int) -> list[float]:
    """S(k) on a uniform grid, k = dk, 2*dk, ... — k=0 excluded."""
    return [structure_factor(i * dk, pts) for i in range(1, n_k + 1)]


def floor_excluding_top(values: list[float], frac: float = 0.01) -> float:
    """Mean of S(k) with the top `frac` removed — the report's definition."""
    keep = sorted(values)[: max(1, int(len(values) * (1.0 - frac)))]
    return sum(keep) / len(keep)


# ---------------------------------------------------------------------------
# A1 — does the grid land on the peaks?
# ---------------------------------------------------------------------------

def test_a1(spacing: float, extent: float) -> None:
    print("=" * 74)
    print("A1  can a grid of dk = %.2f land on the Bragg peaks?" % DK)
    print("=" * 74)

    k_bragg = 2.0 * math.pi / spacing
    width = 2.0 * math.pi / extent
    print("  periodic probe, spacing %.3f over length %.0f" % (spacing, extent))
    print("  first Bragg peak at k = %.4f, spaced %.4f apart" % (k_bragg, k_bragg))
    print("  finite-sample peak width 2*pi/L = %.4f" % width)
    print("  grid spacing dk = %.2f is %.0fx the peak width" % (DK, DK / width))
    print()

    pts = lattice(N_POINTS, spacing)
    hits = misses = 0
    for m in range(1, int(N_K * DK / k_bragg) + 1):
        k = m * k_bragg
        nearest = round(k / DK) * DK
        if abs(nearest - k) <= width / 2.0:
            hits += 1
        else:
            misses += 1
    total = hits + misses
    print("  Bragg peaks in range : %d" % total)
    print("  landed on by the grid: %d" % hits)
    print("  missed entirely      : %d" % misses)
    print()
    print("  S(0) = N = %d by construction, for every point set that exists."
          % N_POINTS)
    print("  It is the one k that is always sampled and always maximal, and")
    print("  it carries no information about order.")
    print()

    if hits:
        print("  NOTE: %d peak(s) are hit, because %.4f / %.2f is near a"
              % (hits, k_bragg, DK))
        print("  rational. Whether a coarse grid hits anything is a")
        print("  commensurability accident between two numbers nobody chose")
        print("  together — which is the failure mode, not an exception to it.")
        vals = sampled_profile(pts, DK, N_K)
        print("  Sampled max here reaches %.0f of a possible %d."
              % (max(vals), N_POINTS))
    print()


# ---------------------------------------------------------------------------
# A2 — which way should the floor go?
# ---------------------------------------------------------------------------

def test_a2(spacing: float, extent: float, rng: random.Random) -> None:
    print("=" * 74)
    print("A2  a pure point spectrum has a floor BELOW the random one")
    print("=" * 74)

    probes = [
        ("Fibonacci (quasiperiodic)", fibonacci_chain(N_POINTS), "pure point"),
        ("Poisson (random)", poisson(N_POINTS, extent, rng), "S(k) -> 1"),
    ]

    print("  %-28s %10s %10s   %s" % ("probe", "mean S(k)", "floor", "expected"))
    results = {}
    for name, pts, expected in probes:
        vals = sampled_profile(pts, DK, N_K)
        fl = floor_excluding_top(vals)
        results[name] = fl
        print("  %-28s %10.2f %10.2f   %s"
              % (name, sum(vals) / len(vals), fl, expected))

    fib = results["Fibonacci (quasiperiodic)"]
    poi = results["Poisson (random)"]
    print()
    print("  quasiperiodic floor / random floor = %.2f" % (fib / poi))
    print()
    print("  The quasiperiodic floor sits FAR BELOW the random one. Between")
    print("  its peaks a pure point spectrum has almost nothing, so a coarse")
    print("  grid that misses the peaks reads a floor near zero — lower than")
    print("  the uncorrelated value of 1, not higher.")
    print()
    print("  SIM-A reports the opposite ordering:")
    print("    Ammann-Beenker floor  2.08")
    print("    cascade floor         0.96   (~1, the correct random asymptote)")
    print()
    print("  The cascade number is right. The AB number is above the")
    print("  uncorrelated floor, and no pure point spectrum produces that.")
    print("  Whatever 2.08 measures, it is not the tiling's structure factor.")
    print()


def main() -> None:
    rng = random.Random(SEED)
    fib = fibonacci_chain(N_POINTS)
    extent = fib[-1]
    spacing = extent / N_POINTS

    print()
    print("APERTURE / ALIASING CONTROL FOR SIM-A")
    print("N = %d points, k-grid dk = %.2f, %d grid points, seed %d"
          % (N_POINTS, DK, N_K, SEED))
    print("1D probes with analytically known spectra. See module docstring")
    print("for what this does and does not establish.")
    print()

    test_a1(spacing, extent)
    test_a2(spacing, extent, rng)

    print("=" * 74)
    print("READING")
    print("=" * 74)
    print("""
  A1 CONFIRMED AS A MECHANISM, with its magnitude configuration-
     dependent. In this run the grid misses 25 of 34 Bragg peaks. The 9
     it lands on are a commensurability accident — the peak spacing
     over the grid spacing happens to sit near 35/3. Move either number
     slightly and the hit count goes to zero. On the Fibonacci probe,
     the quasiperiodic one and the analogue of interest, exactly ONE of
     400 grid samples lands on a strong peak.

     So the honest version is narrower than "only k=0 survives": a
     coarse grid loses most of a point spectrum, loses all of it under
     small changes to numbers nobody chose together, and always keeps
     k=0 — which every point set has and which says nothing about
     order.

  A2 CONFIRMED, and it is the stronger of the two because it does not
     depend on guessing the grid spacing at all. The DIRECTION of the
     floor comparison is fixed by what a pure point spectrum is. Here
     the quasiperiodic floor is 0.09 against a random floor of 0.99,
     an order of magnitude BELOW. SIM-A puts Ammann-Beenker at 2.08,
     twice ABOVE the cascade's 0.96.

  Together these say SIM-A's numbers are properties of the measurement,
  not of the tilings: "68 peaks", the diffuse floor, and the tail
  exponent alpha all describe the apparatus.

  One caveat on the floor, stated because it would change the reading:
  the plain MEAN of the same Fibonacci samples is 2.45, not 0.09,
  because a single sampled peak dominates it. If SIM-A's 2.08 were a
  mean rather than a top-excluded floor, a quasiperiodic set could
  produce it. The figure panel is labelled "Diffuse Background (excl.
  top 1%)", which is the definition used here, so the comparison stands
  as read — but it rests on that label.

  What this does NOT establish: that the drop's S(k) code has this
  specific bug. The generators were not shipped. The one run that would
  settle it is still the one the back-trace names — push the SIM-B
  periodic lattice through the SIM-A code and see whether it, too,
  returns only k=0.

  It also does not revive the cascade side. S(k) -> 1 is the correct
  asymptote for an uncorrelated point set, and 0.96 is what the cascade
  returned.
""")


if __name__ == "__main__":
    main()
