# stability-trigger-envelope/cases.py
#
# CONSTRUCTED fixtures for descent_record.py. No trace here came off a
# vehicle. Every series is generated by the function below, and the expected
# verdicts live in test_envelope.py rather than in this file, so a fixture
# cannot agree with the instrument by construction.
#
# These are REGRESSION fixtures, not validation. They were authored by the
# same hand that wrote the classifier, so they show the planted faults fire
# and show nothing about whether the classifier reads a real descent. That is
# T1, and T1 has not been run.
#
# Standard library only. Parses under Python 3.9.

from __future__ import annotations

import math
from typing import Dict, List, Optional

from descent_record import descent_record, trace

FIXTURE_NOTE = """\
CONSTRUCTED. No tractor, no trailer, no descent, no IMU. The traces below are
generated bursts and the verdicts are statements about the instrument.

The reference case in the work order is a real operator's account, carried at
OBSERVED with N_operators = 1. Nothing in this file is that account: the
fixtures are shaped after it so the planted faults fire, which is a different
thing from reproducing it.

F1 is the configuration the case describes AND the one a phase reading cannot
resolve: the cab leads the trailer by about one curve reversal, and a phase
lead is fixed only modulo one reversal, so a lead of one reversal and a lead
of nothing produce the same correlation peak. The classifier reads onset
timing instead. See RUN_NOTE.md CHOICE 1.
"""

RATE_HZ = 50.0
DURATION_S = 24.0
N = int(RATE_HZ * DURATION_S)          # 1200 samples
REVERSALS = 12                          # -> forcing period 2.0 s, 100 samples
PERIOD_SAMPLES = N / REVERSALS


def burst(n: int, period_samples: float, amp: float, onset_idx: int,
          rise_samples: int) -> List[float]:
    """A carrier at the forcing period under a ramp-and-hold envelope.

    Zero before onset_idx, ramping to amp over rise_samples, held after. The
    carrier is what an accelerometer sees on a serpentine; the envelope is
    what the classifier reads.
    """
    out = []
    for i in range(n):
        if i < onset_idx:
            level = 0.0
        else:
            k = (i - onset_idx) / float(rise_samples)
            if k > 1.0:
                k = 1.0
            level = amp * k
        out.append(level * math.sin(2.0 * math.pi * i / period_samples))
    return out


def _record(cab: Optional[Dict[str, object]],
            trl: Optional[Dict[str, object]], **over) -> Dict[str, object]:
    fields = {"region": "constructed", "road_id": "constructed-road",
              "grade_pct": 11.0, "curve_reversals": REVERSALS,
              "access_count_to_drop": 2, "alternate_route_hours": 3.0,
              "slow_users_present": True, "surface_state": "dry",
              "speed_mph": 30.0, "esp_event_ts": 6.0,
              "downstream_event": "none", "note": "CONSTRUCTED"}
    fields.update(over)
    return descent_record(cab_imu=cab, trailer_imu=trl, **fields)


# --------------------------------------------------------------------------
# F1 -- serpentine, cab-only oscillation          -> GEOMETRIC_CAB_MODE
# --------------------------------------------------------------------------

def f1_cab_mode() -> Dict[str, object]:
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    # the trailer moves a little, one full reversal later: the case's own
    # prediction, and the lead a phase reading cannot resolve
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
    return _record(cab, trl, road_id="constructed-road-1",
                   note="CONSTRUCTED: cab dominant, cab first by one reversal")


# --------------------------------------------------------------------------
# F2 -- real trailer roll                         -> TRAILER_ROLL_RISK
# --------------------------------------------------------------------------

def f2_trailer_roll() -> Dict[str, object]:
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.20, 300, 40))
    return _record(cab, trl, road_id="constructed-road-2",
                   note="CONSTRUCTED: trailer dominant and first")


# --------------------------------------------------------------------------
# F3 -- no trailer IMU                            -> TRAILER_CHANNEL_ABSENT
# --------------------------------------------------------------------------

def f3_no_trailer() -> Dict[str, object]:
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    return _record(cab, None, road_id="constructed-road-3",
                   note="CONSTRUCTED: trailer not instrumented. NOT a quiet "
                        "trailer -- nobody looked.")


# --------------------------------------------------------------------------
# F4 -- clocks misaligned beyond the window       -> NOT_EVALUABLE
# --------------------------------------------------------------------------

def f4_clock_skew() -> Dict[str, object]:
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    trl = trace(0.50, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
    return _record(cab, trl, road_id="constructed-road-4",
                   note="CONSTRUCTED: trailer logger started 0.5 s late, "
                        "against a 0.05 s tolerance")


# --------------------------------------------------------------------------
# F5 -- two runs on a road                        -> INSUFFICIENT_RUNS
# --------------------------------------------------------------------------

def f5_two_runs() -> List[Dict[str, object]]:
    rows = []
    for speed in (31.0, 34.0):
        cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
        trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
        rows.append(_record(cab, trl, road_id="constructed-road-5",
                            speed_mph=speed, esp_event_ts=6.0))
    # a run on the same road where nothing fired: kept, reported apart, and
    # it bounds the edge from below rather than being dropped
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.30, 200, 40))
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.05, 300, 40))
    rows.append(_record(cab, trl, road_id="constructed-road-5",
                        speed_mph=26.0, esp_event_ts=None))
    return rows


# --------------------------------------------------------------------------
# additions beyond the order's five, labelled as such
# --------------------------------------------------------------------------

def f6_out_of_envelope() -> Dict[str, object]:
    """Ice. The reader declares it cannot read there, which is a refusal and
    not a finding that nothing happens on ice -- V5 says the opposite."""
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
    return _record(cab, trl, road_id="constructed-road-6",
                   surface_state="ice",
                   note="CONSTRUCTED: outside the declared reading set")


def f7_axes_disagree() -> Dict[str, object]:
    """Amplitude says cab, onset says the trailer moved first. Two readings
    pointing opposite ways is not a verdict."""
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 300, 40))
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 200, 40))
    return _record(cab, trl, road_id="constructed-road-7",
                   note="CONSTRUCTED: the two axes disagree")


def f8_comparable() -> Dict[str, object]:
    """Both bodies move about the same. The record does not separate them,
    and that is a result rather than a default verdict."""
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.90, 260, 40))
    return _record(cab, trl, road_id="constructed-road-8",
                   note="CONSTRUCTED: comparable amplitudes")


def f9_enough_runs() -> List[Dict[str, object]]:
    """Three runs with a trigger on one road, so envelope_edge returns an
    edge. Exists so INSUFFICIENT_RUNS is shown to be reachable in both
    directions rather than only in the failing one."""
    rows = []
    for speed in (29.0, 32.0, 36.0):
        cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
        trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
        rows.append(_record(cab, trl, road_id="constructed-road-9",
                            speed_mph=speed, esp_event_ts=6.0))
    cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.30, 200, 40))
    trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.05, 300, 40))
    rows.append(_record(cab, trl, road_id="constructed-road-9",
                        speed_mph=24.0, esp_event_ts=None))
    return rows


def tally_set() -> List[Dict[str, object]]:
    """A set for relocation_tally. Downstream events and access counts are
    varied so every bin is exercised; the counts are constructed and are not
    a rate of anything."""
    spec = [("none", 4), ("pass", 2), ("near_miss", 1), ("near_miss", 2),
            ("incident", 1), ("closure", 1), ("closure", 2), ("pass", 6),
            ("none", 6)]
    rows = []
    for i, pair in enumerate(spec):
        event, access = pair
        cab = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 1.00, 200, 40))
        trl = trace(0.0, RATE_HZ, burst(N, PERIOD_SAMPLES, 0.15, 300, 40))
        rows.append(_record(cab, trl, road_id="constructed-road-t%d" % i,
                            access_count_to_drop=access,
                            downstream_event=event))
    return rows


#: name, builder, expected verdict. The expectations are repeated in
#: test_envelope.py; this table is for the render only.
FIXTURES = [
    ("F1 serpentine, cab-only oscillation", f1_cab_mode, "GEOMETRIC_CAB_MODE"),
    ("F2 real trailer roll", f2_trailer_roll, "TRAILER_ROLL_RISK"),
    ("F3 no trailer IMU", f3_no_trailer, "TRAILER_CHANNEL_ABSENT"),
    ("F4 clocks misaligned", f4_clock_skew, "NOT_EVALUABLE"),
    ("F5 two runs on a road", f5_two_runs, "INSUFFICIENT_RUNS"),
    ("F6 ice (addition)", f6_out_of_envelope, "OUT_OF_ENVELOPE"),
    ("F7 axes disagree (addition)", f7_axes_disagree, "NOT_EVALUABLE"),
    ("F8 comparable amplitudes (addition)", f8_comparable, "NOT_EVALUABLE"),
]
