#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
"""
transmission_cascade -- WO-8, the join of two literatures, built to the
order and run on CONSTRUCTED data. No dataset is recoded; the modules
score coder labels, layer distributions and condition-change responses
supplied to them, all generated by a declared model.

  Literature A  organizational cascade (depth, outcome measures,
                identification-with-leader as a POSTURE moderator)
  Literature B  cultural-evolution transmission TYPES
                (stimulus enhancement / emulation / imitation /
                 overimitation)
  the join      code a multi-level cascade by transmission TYPE

The order's decisive prediction: under a condition change a copied-STEPS
transmission (overimitation) has nothing to recompute from; an emulation
or principle transmission does. Types look alike under stable conditions
and separate only when conditions change.

cohen_kappa is imported from effective-redundancy-audit, not copied.

Python 3.9, ASCII only, stdlib only. Refuses --selftest; the checks live
in test_cascade.py.
"""

from __future__ import annotations

import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "effective-redundancy-audit"))
from effective_redundancy import cohen_kappa   # noqa: E402  (imported, not copied)

TYPES = ("STIMULUS_ENHANCEMENT", "EMULATION", "IMITATION", "OVERIMITATION")
# the two types that carry a generating principle vs the two that do not,
# per the order: emulation copies the RESULT (recomputable), overimitation
# copies ALL STEPS with no access to why (not recomputable). imitation and
# stimulus enhancement sit between and are entered as coded.
RECOMPUTABLE = {"STIMULUS_ENHANCEMENT": None, "EMULATION": True,
                "IMITATION": False, "OVERIMITATION": False}

STATUS = ("OBSERVED", "DERIVED", "PROPOSED", "CONSTRUCTED")

KAPPA_FLOOR = 0.60                                           # [CHOICE 1]
MATERIAL = 0.10                                              # [CHOICE 5]

CHOICES = {
    1: "R2 gates R1: below a coder-agreement floor of 0.60 the taxonomy is "
       "not reliably applied and R1 is UNINTERPRETABLE, which is the finding",
    2: "the recompute/repeat outcome is a declared response field; a run "
       "with neither is NOT_EVALUABLE, not a repeat",
    3: "R4 enters identification-with-leader alongside transmission type as "
       "a two-predictor linear fit on the recompute outcome; type adds "
       "nothing iff its coefficient does not survive identification entering",
    4: "the two literatures' join is PROPOSED; the taxonomy's transfer from "
       "children-and-toolmaking to adult hierarchy is itself unvalidated "
       "and is the object R2 tests, not an assumption",
    5: "R4 counts type as surviving only if its coefficient stays material "
       "(|b| >= 0.10) with identification entered; a relative-only test "
       "passes on noise near zero",
}


class Refused(ValueError):
    """Raised at intake. A refused record never reaches a readout."""


def absent(v):
    return v is None or v == "" or v == "UNDECLARED"


# ===================================================== R2 -- coder gate first

def r2_reliability(coder1, coder2):
    """Cohen's kappa between two coders' type labels, blind to layer and
    outcome. Gates R1: below the floor R1 is uninterpretable."""
    if len(coder1) != len(coder2) or not coder1:
        raise Refused("r2_reliability: aligned non-empty label lists")
    for lab in list(coder1) + list(coder2):
        if lab not in TYPES:
            raise Refused("r2_reliability: %r is not a transmission type" % (lab,))
    k = cohen_kappa(list(coder1), list(coder2))
    return {"kappa": k, "floor": KAPPA_FLOOR,
            "gate": "R1_INTERPRETABLE" if k >= KAPPA_FLOOR
            else "R1_UNINTERPRETABLE",
            "reads": ("the taxonomy applies reliably to this material"
                      if k >= KAPPA_FLOOR else
                      "the taxonomy does not code this material reliably; "
                      "that the taxonomy is domain-bound is the finding")}


# ===================================================== R1 -- type by layer

def r1_distribution(events, reliability):                   # [CHOICE 1]
    """events: list of dicts {layer, type}. Returns the count of each type
    per layer, but ONLY if R2 cleared the floor. Below it, the distribution
    is withheld and the gate verdict is returned instead."""
    if reliability["gate"] == "R1_UNINTERPRETABLE":
        return {"gate": "R1_UNINTERPRETABLE", "distribution": None,
                "reads": reliability["reads"]}
    dist = {}
    for e in events:
        if e["type"] not in TYPES:
            raise Refused("r1_distribution: %r is not a type" % (e["type"],))
        dist.setdefault(e["layer"], {t: 0 for t in TYPES})[e["type"]] += 1
    return {"gate": "R1_INTERPRETABLE", "distribution": dist,
            "layers": sorted(dist)}


# ============================================ R3 -- condition-change probe

def r3_recompute(runs):                                     # [CHOICE 2]
    """runs: list of {type, response} after a condition change makes the
    behaviour no longer serve its purpose. response in {'recompute',
    'repeat'}; anything else is NOT_EVALUABLE. Returns the recompute share
    per type and whether it tracks RECOMPUTABLE."""
    by = {t: {"recompute": 0, "repeat": 0, "uneval": 0} for t in TYPES}
    for r in runs:
        if r["type"] not in TYPES:
            raise Refused("r3_recompute: %r is not a type" % (r["type"],))
        resp = r.get("response")
        if resp == "recompute":
            by[r["type"]]["recompute"] += 1
        elif resp == "repeat":
            by[r["type"]]["repeat"] += 1
        else:
            by[r["type"]]["uneval"] += 1
    out = {}
    for t in TYPES:
        n = by[t]["recompute"] + by[t]["repeat"]
        out[t] = {"recompute_share": None if n == 0 else by[t]["recompute"] / n,
                  "n": n, "uneval": by[t]["uneval"]}
    # the order's prediction: overimitation repeats, emulation recomputes
    em = out["EMULATION"]["recompute_share"]
    ov = out["OVERIMITATION"]["recompute_share"]
    if em is None or ov is None:
        verdict = "NOT_EVALUABLE (a decisive type has no scored runs)"
    elif em > ov:
        verdict = "type predicts response (emulation recomputes above overimitation)"
    else:
        verdict = ("type does not predict the response; the taxonomy does "
                   "not transfer and R1's value is descriptive only")
    return {"by_type": out, "verdict": verdict,
            "emulation_share": em, "overimitation_share": ov}


# =========================== R4 -- identification-with-leader as competitor

def _ols2(y, x1, x2):
    """Two-predictor least squares with intercept, by hand. Returns
    (b0, b1, b2) or None if singular."""
    n = len(y)
    X = [[1.0, x1[i], x2[i]] for i in range(n)]
    A = [[sum(X[i][a] * X[i][b] for i in range(n)) for b in range(3)]
         + [sum(X[i][a] * y[i] for i in range(n))] for a in range(3)]
    for c in range(3):
        piv = max(range(c, 3), key=lambda r: abs(A[r][c]))
        if abs(A[piv][c]) < 1e-12:
            return None
        A[c], A[piv] = A[piv], A[c]
        pv = A[c][c]
        for j in range(c, 4):
            A[c][j] /= pv
        for r in range(3):
            if r != c and A[r][c] != 0.0:
                f = A[r][c]
                for j in range(c, 4):
                    A[r][j] -= f * A[c][j]
    return A[0][3], A[1][3], A[2][3]


def r4_competing(rows):                                     # [CHOICE 3]
    """rows: list of {type, identification, recompute}. Enters
    is-overimitation and identification together on the recompute outcome.
    Type 'adds nothing' iff its coefficient collapses toward zero once
    identification is entered."""
    y = [1.0 if r["recompute"] else 0.0 for r in rows]
    over = [1.0 if r["type"] == "OVERIMITATION" else 0.0 for r in rows]
    idn = [float(r["identification"]) for r in rows]
    n = len(rows)
    mo = sum(over) / n
    soo = sum((o - mo) ** 2 for o in over)
    my = sum(y) / n
    b_solo = (None if soo == 0 else
              sum((over[i] - mo) * (y[i] - my) for i in range(n)) / soo)
    both = _ols2(y, over, idn)
    if b_solo is None or both is None:
        return {"verdict": "NOT_EVALUABLE (singular design)",
                "type_alone": None, "type_with_identification": None}
    b_both = both[1]
    # survives iff the coefficient stays MATERIAL (>= floor) and keeps its
    # sign; a relative-only test passes trivially when both are noise near
    # zero, so an absolute floor is required. [CHOICE 5]
    survives = (abs(b_both) >= MATERIAL and abs(b_both) > 0.5 * abs(b_solo)
                and b_both * b_solo > 0)
    return {"type_alone": b_solo, "type_with_identification": b_both,
            "identification_coef": both[2],
            "verdict": ("transmission type survives identification entering"
                        if survives else
                        "type adds nothing once identification is entered")}


# =============================================== constructed worlds (declared)

def cascade_events(seed=3):
    """CONSTRUCTED three-level cascade coded by type. Overimitation rises
    with layer; emulation falls -- a declared shape, not a finding."""
    rng = random.Random(seed)
    mix = {1: (0.1, 0.4, 0.3, 0.2), 2: (0.1, 0.25, 0.3, 0.35),
           3: (0.05, 0.1, 0.25, 0.6)}
    events = []
    for layer, p in mix.items():
        for _ in range(80):
            events.append({"layer": layer,
                           "type": rng.choices(TYPES, weights=p)[0]})
    return events


def two_coders(events, agree=0.85, seed=5):
    """Two coder label lists over the events, agreeing at `agree`."""
    rng = random.Random(seed)
    c1 = [e["type"] for e in events]
    c2 = []
    for lab in c1:
        if rng.random() < agree:
            c2.append(lab)
        else:
            c2.append(rng.choice([t for t in TYPES if t != lab]))
    return c1, c2


def condition_runs(seed=11, n=60):
    """CONSTRUCTED condition-change runs: overimitation repeats, emulation
    recomputes, the middle types in between -- the order's prediction as a
    declared generative model, so R3 is a known-answer run on the scorer."""
    rng = random.Random(seed)
    p_recompute = {"STIMULUS_ENHANCEMENT": 0.5, "EMULATION": 0.8,
                   "IMITATION": 0.35, "OVERIMITATION": 0.1}
    runs = []
    for t in TYPES:
        for _ in range(n):
            resp = "recompute" if rng.random() < p_recompute[t] else "repeat"
            runs.append({"type": t, "response": resp})
    return runs


def competing_rows(seed=13, n=240, type_effect=0.4, id_effect=0.0):
    """CONSTRUCTED rows where recompute depends on type (and optionally on
    identification). With id_effect=0 the type coefficient must survive."""
    rng = random.Random(seed)
    rows = []
    for _ in range(n):
        t = rng.choice(TYPES)
        idn = rng.random()
        base = 0.5
        p = base - (type_effect if t == "OVERIMITATION" else 0.0) + id_effect * (idn - 0.5)
        rows.append({"type": t, "identification": idn,
                     "recompute": rng.random() < max(0.0, min(1.0, p))})
    return rows


# ------------------------------------------------------------------ render

def refuse_selftest(name):
    sys.stderr.write("%s carries no selftest; run python3 test_cascade.py\n"
                     % name)
    return 2


def render():
    ev = cascade_events()
    c1, c2 = two_coders(ev)
    rel = r2_reliability(c1, c2)
    out = ["WO-8  TRANSMISSION-TYPE CASCADE   (data CONSTRUCTED, PROPOSED; "
           "no dataset recoded)", "-" * 72,
           "R2  coder gate FIRST   [CHOICE 1]",
           "    kappa %.3f  floor %.2f -> %s" % (rel["kappa"], rel["floor"], rel["gate"]),
           ""]
    r1 = r1_distribution(ev, rel)
    out.append("R1  type by layer (gated on R2)")
    if r1["distribution"] is None:
        out.append("    withheld: %s" % r1["reads"])
    else:
        for layer in r1["layers"]:
            d = r1["distribution"][layer]
            out.append("    layer %d  " % layer + "  ".join(
                "%s %d" % (t[:4], d[t]) for t in TYPES))
    out.append("")
    r3 = r3_recompute(condition_runs())
    out.append("R3  condition-change recompute share by type   [CHOICE 2]")
    for t in TYPES:
        s = r3["by_type"][t]
        out.append("    %-22s %s  (n %d)" % (
            t, "None" if s["recompute_share"] is None else "%.3f" % s["recompute_share"], s["n"]))
    out.append("    -> %s" % r3["verdict"])
    out.append("")
    r4a = r4_competing(competing_rows(id_effect=0.0))
    r4b = r4_competing(competing_rows(id_effect=0.8, type_effect=0.0))
    out.append("R4  identification-with-leader entered alongside type   [CHOICE 3]")
    out.append("    type real, id null:   type alone %+.3f  with id %+.3f -> %s"
               % (r4a["type_alone"], r4a["type_with_identification"], r4a["verdict"]))
    out.append("    id real, type null:   type alone %+.3f  with id %+.3f -> %s"
               % (r4b["type_alone"], r4b["type_with_identification"], r4b["verdict"]))
    out.append("")
    out.append("scope [CHOICE 4]: the taxonomy's transfer to adult hierarchy "
               "is itself unvalidated and is what R2 tests")
    return "\n".join(out) + "\n"


def main(argv):
    if "--selftest" in argv:
        return refuse_selftest("transmission_cascade.py")
    if "--choices" in argv:
        for k in sorted(CHOICES):
            sys.stdout.write("[CHOICE %d] %s\n" % (k, CHOICES[k]))
        return 0
    sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
