#!/usr/bin/env python3
"""mechanism_10_audit.py -- checks on MECHANISM 10, GENERATION CAPACITY REMOVED.

Added, not delivered. MECHANISM_10.md is the drop as received and is not
modified. Findings are recorded in AUDIT_NOTES.md as GC_001..GC_007.

    python3 mechanism_10_audit.py

The mechanism makes one claim that is directly checkable against an
instrument already in this repo: "a binary that passes an option-space
audit truthfully". ../presented-binary/binary_audit.py is an option-space
audit. Section 1 runs it.

Nothing here quantifies R1, R2 or R3. The drop says no case has readings
and this audit does not invent one.

stdlib only, deterministic. CC0.
"""

import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BAR = "=" * 70


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BA = _load("binary_audit", os.path.join(ROOT, "presented-binary", "binary_audit.py"))
import capacity as CAP  # the delivered scorer, arrived in drop 2

# The nine mechanisms already in play: eight in uninstrumented/README.md
# plus category-weld's proposed ninth. Each with what it requires to exist,
# so distinctness is checked against structure rather than against a label.
NINE = [
    ("MODALITY", "apparatus is in a different channel from the quantity"),
    ("STORAGE", "medium cannot hold the shape of the quantity"),
    ("SCALAR DEMAND", "one quantity's variation over a domain flattened to a scalar"),
    ("BUDGET BOUNDARY", "a closed budget compared against an open one"),
    ("AUTHORED REFERENCE", "the reference is produced by the MEASURED party"),
    ("PROXY SUBSTITUTION", "a named target displaced by a named enforceable stand-in"),
    ("AUDIT ASYMMETRY", "the guard fires on one side of a comparison only"),
    ("SCORED AS WASTE", "a component enters the accounting as cost"),
    ("CATEGORY WELD", "two measurable quantities fused into one handle"),
]

# A framing under MECHANISM 10, answered honestly. Every answer is what the
# affected party would truthfully give: the options really were generated
# by them, the search really was widened, the constraint really does hold.
HONEST = {
    "case": "under-mechanism-10",
    "presented_as": "two options",
    "source": "constructed for this audit, not a documented incident",
    "checks": {
        "O1": {"state": "documented", "answer": "two",
               "record": "generation session minuted"},
        "O2": {"state": "documented", "answer": "three weeks",
               "record": "calendar"},
        "O3": {"state": "documented",
               "answer": "generated by the affected party; all inside the set",
               "record": "attendance list"},
        "O4": {"state": "documented", "answer": "attempt recorded, not only result",
               "record": "minutes"},
        "O5": {"state": "documented",
               "answer": "widened twice; returned nothing new",
               "record": "second and third session minutes"},
        "O6": {"state": "documented",
               "answer": "each constraint held under push; FOUND, not authored",
               "record": "transcript"},
        "S1": {"state": "documented", "answer": "selected by the affected party, inside it",
               "record": "vote record"},
        "S2": {"state": "documented", "answer": "counted by functional position",
               "record": "role inventory"},
        "S3": {"state": "documented", "answer": "no-sacrifice branch specified in advance",
               "record": "pre-registration"},
        "S4": {"state": "documented", "answer": "post-audit scheduled, owner named",
               "record": "schedule"},
        "S5": {"state": "documented", "answer": "wrong-call condition stated in advance",
               "record": "pre-registration"},
    },
}


def head(n, cid, title):
    print()
    print(BAR)
    print("%-2d %s  %s" % (n, cid, title))
    print(BAR)


print("generation-capacity -- audit of MECHANISM 10")
print("delivered: MECHANISM_10.md (marker under exploration)")
print("instrument borrowed for section 1: ../presented-binary/binary_audit.py")

# ------------------------------------------------------------------ GC_001
head(1, "GC_001", "the claim that a binary under this mechanism passes an audit")
print("""
MECHANISM_10.md, VISIBLE AS:

    A binary that passes an option-space audit truthfully. Two alternatives
    generated, because two is the ceiling of what the party's remaining
    knowledge can produce.

presented-binary/binary_audit.py is an option-space audit with eleven
checks. Answered honestly by a party under this mechanism -- every answer
true, every answer with a record behind it:
""".strip())
s = BA.score(HONEST)
print()
for cid, block, q in BA.CHECKS:
    e = HONEST["checks"][cid]
    print("  %-3s [%-10s] %s" % (cid, e["state"], e["answer"]))
print()
print("  documented %d   asserted %d   absent %d   documented_share %.3f" % (
    s["documented"], s["asserted"], s["absent"], s["documented_share"]))
print()
print("""
11 of 11 documented. The claim holds against the instrument as delivered.

O3 is the cell the mechanism is aimed at. It asks "who generated them, and
are they inside the affected set?" and it exists to catch options
generated by people who do not carry the consequences. Under MECHANISM 10
the options ARE generated by the affected party, so O3's answer is the one
that reassures -- and that answer is the mechanism's signature, not its
absence. O5 is the second: widening a search over a reduced generator
returns nothing new, which reads as confirmation that the set was
complete.

The mechanism understates its own case, though, and the understatement is
worth measuring. binary_audit computes no verdict; documented_share is the
share of checks with a RECORD behind them and never reads what the record
says. So the same eleven checks, answered damningly with full records:
""".strip())
ids = [c[0] for c in BA.CHECKS]
for label, ans in (("favourable", "reassuring on every check"),
                   ("damning", "outsiders decided, constraint converted to urgency")):
    c = {"case": label,
         "checks": {i: {"state": "documented", "answer": ans, "record": "r"}
                    for i in ids}}
    sc = BA.score(c)
    print("  %-12s documented %2d   documented_share %.3f" % (
        label, sc["documented"], sc["documented_share"]))
print()
print("""
Identical. The pass is over-determined: a framing under MECHANISM 10 does
not need its answers to come out favourable, because the instrument's only
number does not grade answers. VISIBLE AS claims the audit is passed on
the merits; it is passed before the merits are reached.

That is a joint reading, not two separate findings. binary_audit's own
docstring is explicit that it computes no verdict and reports how much of
the framing has a record behind it -- which is a deliberate and defensible
scope. The consequence is that "passes an option-space audit" is a weaker
statement than it sounds, and MECHANISM 10 would still pass an instrument
that DID grade answers, for the reason the mechanism gives.

Either way it is not a defect in any check. All eleven ask about the
decision episode, and the removal happened before it, on a clock the
answering party has no access to. An audit of the episode cannot reach it.
""".strip())

# ------------------------------------------------------------------ GC_002
head(2, "GC_002", "ANSWERED -- the drop built a router, not a twelfth check")
print("""
The first pass argued the gap cannot be closed by adding a check to
binary_audit's option_space block, because documented / asserted / absent
resolve against the answering party's own record and an absent generator
produces an absent record of itself. The conclusion was that MECHANISM 10
needs a second instrument beside binary_audit rather than another row.

The drop built exactly that: capacity.py, plus a handoff() router in
binary_audit that hands a case across when O1 comes back honest at a low
count. Measured, on the delivered router:
""".strip("\n"))
print()
print("  %-42s %s" % ("O1 state", "handoff"))
print("  " + "-" * 72)
for label, st, count in [
    ("documented, count 2 -- the signature", "documented", 2),
    ("documented, count not stated", "documented", None),
    ("absent", "absent", None),
]:
    ch = {i: {"state": "absent", "answer": "", "record": ""}
          for i in [c[0] for c in BA.CHECKS]}
    ch["O1"] = {"state": st, "answer": "", "record": ""}
    if count is not None:
        ch["O1"]["count"] = count
    h = BA.score({"case": "probe", "checks": ch})["handoff"]
    shown = ("-> %s" % h["route"]) if (h and h.get("route")) else (
        ("not routed: %s" % h["reason"]) if h else "None")
    print("  %-42s %s" % (label, shown))
print()
print("""
The router's docstring states the reasoning the first pass reached
independently: "An option-space audit closing clean on a low DOCUMENTED
count is the signature of removed generation capacity, not evidence of its
absence." And it refuses to estimate -- O1 documented without a stated
count returns not-routed with a reason rather than a guess.

GC_002 is ANSWERED rather than refuted: the argument was that the repair
is a second instrument, and the repair delivered is a second instrument.
What the router does with its own negative branch is a separate matter,
recorded in presented-binary PB_012.
""".strip())

# ------------------------------------------------------------------ GC_003
head(3, "GC_003", "R1's two named denominators are not interchangeable")
print("""
    R1 -- recall ratio. Nameable / present, per place, per generation.
    Denominator from ethnobotanical and floristic inventories, which
    exist. Numerator from resident recall, which is not collected against
    them.

    ... it is a collection gap rather than a method gap.

The two named sources break in different places, and neither is the
denominator the ratio needs as stated.

  FLORISTIC inventory
    Linnaean, produced by the center, independent of resident recall --
    so it is a genuine independent denominator, which is what the ratio
    needs. But scoring resident recall against it requires mapping local
    names onto species: a resident naming one plant where the inventory
    splits three, or three where it lumps one. That mapping IS scoring
    against a central reference, which the CALIBRATION CONSTRAINT four
    paragraphs earlier forbids.

  ETHNOBOTANICAL inventory
    Collected from residents, so the mapping problem does not arise --
    the units already match. But it inherits the recall of whoever was
    surveyed when it was made. Measuring recall against it is measuring
    recall against earlier recall, which is R2 (transmission interval),
    not R1. It cannot supply an independent denominator because it is a
    numerator from a previous generation.

Stated as a fork: the independent denominator needs a translation step the
constraint forbids, and the translatable denominator is not independent.

This does not sink R1. It relocates the gap: part of what the drop files
under collection is a method question about what counts as one nameable
item, and it has to be settled before a numerator is collected, not after.
The drop's own constraint is what surfaces it.
""".strip("\n"))
print()
print("""
AGAINST THE DELIVERED CODE. capacity.py implements the calibration
constraint as a `scored_against` field: set to `center`, the reading is
flagged invalid and dropped from the slope. That closes the case the
CALIBRATION CONSTRAINT names explicitly, and the selftest covers it.

It is a DECLARATION, not a unit check. Nothing reads source_present or
source_nameable, so a case can declare `place` and still count its
denominator in Linnaean species and its numerator in local names:
""".strip())
mixed = {"name": "mixed-units", "domain": "probe", "generations": [
    {"label": "g1", "present": 120, "nameable": 40, "scored_against": "place",
     "source_present": "floristic inventory, Linnaean species",
     "source_nameable": "resident free recall, local names"},
    {"label": "g2", "present": 120, "nameable": 12, "scored_against": "place",
     "source_present": "floristic inventory, Linnaean species",
     "source_nameable": "resident free recall, local names"},
]}
sm = CAP.score(mixed)
print()
print("  declared place, mismatched units -> slope %s, invalid_scoring %d" % (
    CAP.fmt(sm["r1_slope"]), sm["invalid_scoring"]))
print()
print("""
The drop's DISCLOSED WEAKNESSES names the numerator half of this -- free
recall against prompted against recognition against demonstrated use give
different numbers and the schema does not distinguish them. The
denominator half is not named, and it is the half the CALIBRATION
CONSTRAINT is actually about: what counts as ONE present item is a
question the center answers.

THE CHECK THE SCHEMA CAN ALREADY MAKE. R1 is nameable / present and cannot
exceed 1 when the two are counted in the same units. Local categories
splitting finer than the inventory, or an incomplete inventory, push it
over:
""".strip())
over = {"name": "over-one", "domain": "probe", "generations": [
    {"label": "g1", "present": 40, "nameable": 55, "scored_against": "place"}]}
r = CAP.r1(over)[0]
print()
print("  present 40, nameable 55 -> ratio %.3f, valid %s, no warning" % (
    r["ratio"], r["valid"]))
print()
print("""
A ratio above 1 is a unit mismatch, computable from the two fields the
schema already carries, and it needs no new concept -- detail() already
prints a WARNING block for center-scored readings and could carry this in
the same place.

G7's stated falsifier is "a methodological barrier to collecting resident
recall against a floristic inventory that is not a funding or attention
barrier". The name-mapping problem is proposed as one. Whether it fires
G7's falsifier turns on whether settling the unit of a nameable item
counts as methodological or as part of collection -- a question for the
author, not one this audit settles.
""".strip())

# ------------------------------------------------------------------ GC_004
head(4, "GC_004", "R3's two outcomes are 'yes' and 'not found'")
print("""
    R3 -- loop check. Is the resulting deficit cited as grounds for the
    gate that produced it. Binary, evidenced by citation or absent.

Evidenced by citation, or absent. A citation that was never searched for
and a citation that does not exist both return absent. The negative
outcome is not reachable by the stated procedure -- there is no state that
means "looked, and the deficit is not cited".

null-harness grades this shape CONSTANT_SILENT on the negative branch: the
readout can confirm the loop and cannot disconfirm it.

The repair is the one R1 already has and R3 does not: a denominator. Name
the corpus searched -- which decision records, over which interval -- so
that zero citations in a named corpus is a measurement and zero citations
in no corpus is a gap. binary_audit.py's O4 already works this way -- it
asks whether a record of the generation attempt EXISTS, not what it says.

R1 and R2 are declared untested; R3 is declared specified. This is a
statement about the specification.
""".strip("\n"))

# ------------------------------------------------------------------ GC_005
head(5, "GC_005", "distinctness against the nine, by structure")
print()
for label, structure in NINE:
    print("  %-20s %s" % (label, structure))
print()
print("""
The two that get closest run in opposite directions and neither closes.

AUDIT ASYMMETRY is "the guard fires on one side of a comparison only". The
LOOP FORM is an asymmetry that becomes its own justification, which is
close -- but AUDIT ASYMMETRY is about a guard's behaviour at audit time,
and here there is no guard misfiring. The audit runs correctly on both
sides (section 1) and the asymmetry is upstream of it.

AUTHORED REFERENCE is "the reference is produced by the MEASURED party" --
a model authoring the benchmark it is scored on. The CALIBRATION
CONSTRAINT names the mirror image: the reference is produced by the party
whose gate created the deficit, and the measured party is the one scored
against it. Same defect in the reference, opposite direction of authorship.

That mirror is worth stating as its own line rather than folding into
either mechanism, because the remedies differ. AUTHORED REFERENCE is
repaired by an external fixed reference (anchor-interval ANC_005..008,
criteria-drift CD_008). This one is made WORSE by an external fixed
reference, if the external reference is the center's -- which is exactly
what the CALIBRATION CONSTRAINT says.

MECHANISM 10 is distinct on the check as written. What would fold it back
in: showing a case where the generator was reduced AND the reduction is
carried somewhere in the record, since then it is a suppression at
decision time and the drop's own EXCLUDED BY paragraph rules it out.
""".strip())

# ------------------------------------------------------------------ GC_006
head(6, "GC_006", "SELF-MAINTAINING is a rate claim and it is already modelled")
print("""
    Active restriction needs continuous expenditure; a removed generator
    needs none. The arrangement persists at zero maintenance cost, which
    is why it outlasts the conditions that produced it.

This is the strongest sentence in the drop, because it is a claim about
cost asymmetry rather than about anyone's conduct, and this repo already
has two instruments shaped for it.

  rigidification-sensor/simulator.py records per tick a `continuation`
  cost and a `reversal` cost, and reports `locked_at` -- the first tick
  where reversal exceeds continuation AND the derivative does too. Zero
  maintenance cost is continuation -> 0, which sends the ratio to the lock
  condition without anything being done. The folder states throughout that
  "control" means control PARAMETER, not a hand on a knob, which is the
  same "no intent required" the LOOP FORM states.

  sustained-activation-gate/ is a tilted double well: the system stays in
  a basin at zero drive, and getting out costs a Kramers escape. A removed
  generator is the well that needs no one holding the system in it.

Neither is a metaphor for the other -- they are the same rate comparison
in three vocabularies. What connects them concretely: R2 (transmission
interval) is the time axis those two simulators run on, and a measured R2
would give the lock check an interval instead of a tick index.

Recorded as an available instrument, not as a result. Nothing has been run.
""".strip("\n"))

# ------------------------------------------------------------------ GC_007
head(7, "GC_007", "the consent claim is the load-bearing one and is not measured")
print("""
    A party rendered unable to generate the alternative cannot consent
    against it. Consent is structurally unavailable while the framing
    still reads as a hard choice made responsibly. This is stronger than
    "the framing is unaudited": the audit's subject cannot be constituted.

Section 1 supports the second sentence as far as the instrument reaches:
the framing scores 11 of 11 documented, so "reads as a hard choice made
responsibly" is a number here rather than a characterisation. With the
qualification section 1 established -- that number grades record
completeness, not the merits of the answers, so what it establishes is
that the framing survives the audit intact, not that the audit approved
of it.

The first sentence is a different kind of claim. "Cannot consent against
an option it cannot generate" is close to analytic -- consent to forgo X
requires X to be available to consider -- and what makes it empirical is
the antecedent: WAS the party unable to generate it. That is R1, and R1
has no readings.

So the chain is: R1 (unmeasured) -> inability (unestablished) -> consent
unavailable (follows). The last step is the cheap one. The drop's own
CONFIDENCE section says as much, and this section records that the load
is concentrated entirely in R1's numerator rather than spread across the
three readouts.

The seed case is chosen well for this: edible species has an existing
denominator and a collectable numerator, and the collection is a survey,
not an experiment. What it does not have yet is GC_003's units decision.
""".strip("\n"))

# ------------------------------------------------------------------ GC_008
head(8, "GC_008", "G3's status names an instrument this repo has")
print("""
    G3. The arrangement requires no ongoing enforcement once capacity is
    gone.
    Status: untested. Requires an enforcement-cost series, which this
    repo has no instance of.

GC_006 in the first pass named two instruments for exactly this rate
comparison, and one of them produces the series G3 says is absent.
rigidification-sensor/simulator.py, run():

    continuation   : current total imbalance -- the bill this tick
    reversal       : cumulative eroded regen -- capacity you'd rebuild to undo
    d_continuation : change in continuation vs last tick
    d_reversal     : change in reversal vs last tick
    locked_at      : first tick where reversal outpaces continuation AND
                     exceeds it

`continuation` IS an enforcement-cost series: the per-tick bill for
holding the arrangement where it is. G3 says that bill drops to zero once
capacity is gone, and G3's falsifier says a case where it stays flat or
rises refutes the claim. That is a statement about the shape of a series
run() already returns.

What the repo does not have is a MEASURED series -- a real arrangement
with a real enforcement cost per interval. The simulator produces one from
declared node parameters, so wiring MECHANISM 10's loop form into it would
test the claim's internal consistency, not the world.

So G3's status is right in substance and wrong in its reason. Not
"requires an instrument this repo has no instance of" but "requires a
measured series; the instrument is in rigidification-sensor/". The
distinction matters because it changes what the next step is -- collect an
enforcement-cost series, rather than build a simulator.
""".strip())

# ------------------------------------------------------------------ GC_009
head(9, "GC_009", "the second seed case is named three times and absent")
print("""
    README STATE:          "Two seed cases, zero quantified readings."
    CLAIM_TABLE weakness:  "Both seeds are structural."
    G2 status:             "argued, one case marked (food-knowledge, push
                            results asserted not recorded)."
""".strip("\n"))
print()
files = sorted(f for f in os.listdir(os.path.join(HERE, "cases"))
               if f.endswith(".json"))
print("  cases/ holds %d: %s" % (len(files), ", ".join(files)))
print()
print("""
food-knowledge is the case the README's worked instance is written about
-- "someone who can name what is edible around them ... never faced two
options" -- and it is the case G2's status reports a reading from. It is
also the case that would fire the handoff router, which currently has no
worked instance (presented-binary PB_013).

Third consecutive drop in which a claim table's status sentence names a
file the drop does not carry: category-weld CW_001 (weld.py, test_weld.py
-- arrived one drop later), presented-binary PB_001 (the seeded case --
arrived this drop, exact), and this. The pattern so far is that the named
files are real and arrive late, so this is recorded as UNVERIFIED rather
than as a negative.

It is left absent rather than reconstructed. G2's status says its push
results are "asserted not recorded", which is a judgement about a specific
case, and writing one here would put that judgement in the author's mouth.
""".strip())


# ------------------------------------------------------------------ GC_010
head(10, "GC_010", "SUBCASE 10A builds the repair five folders have needed")
print("""
SUBCASE_10A.md specifies three readouts. S1:

    S1 -- ledger check. In the documented justification for a destructive
    reading, is the set of foreclosed future readings (a) absent,
    (b) entered as zero or negligible, or (c) entered as unknown and
    unbounded? Three-valued, evidenced by citation from the record.
    ABSENT AND ZERO ARE DISTINGUISHABLE: absent means the term never
    appeared, zero means it appeared and was discounted.

That last sentence is the repair this audit has recorded four times, in
four folders, against instruments that shipped without it:
""".strip())
print()
for cid, where, what in [
    ("PB_004", "frame_sim option_gain",
     "wide pass found 0 options == wide pass never ran"),
    ("PB_012", "binary_audit handoff()",
     "count above ceiling == O1 never checked"),
    ("GC_004", "MECHANISM_10 R3",
     "no citation found == no corpus searched"),
    ("MD_002", "moral-decomposer reduces_to",
     "irreducible residue == routed elsewhere"),
]:
    print("  %-8s %-28s %s" % (cid, where, what))
print()
print("""
Each of those is one value standing for a measurement and for the absence
of the measurement. S1 separates them in the specification, before any
code exists, and says why in the same sentence.

It is worth being precise about what this does and does not show. S1 has
no implementation and no reading, so this is not evidence that the
distinction survives contact with a record. What it shows is that the
distinction was designed in rather than retrofitted, which is the only
point in the cycle where it is free.

S2 and S3 carry the same shape. S2 is binary but its negative branch is
"the record does not state whether the source survives", which is a
finding rather than a gap -- "a record that does not state this cannot
have weighed it". S3 is three-valued on the same absent/rejected/not-
enumerated axis and routes its third value to presented-binary.
""".strip())

# ------------------------------------------------------------------ GC_011
head(11, "GC_011", "the sub-case sharpens GC_003 rather than repeating it")
print("""
GC_003 found R1's denominator problem in the parent: floristic inventory
is independent but needs a local-name-to-species mapping the CALIBRATION
CONSTRAINT forbids; ethnobotanical inventory is translatable but is a
previous generation's numerator. A units question inside what the drop
filed as a collection gap.

SUBCASE_10A names a different failure at the same site and distinguishes
the two correctly:

    In the parent case the denominator survives: the plants are still
    growing whether or not anyone can name them, so the ratio is
    recoverable in principle and the gap is a collection gap.

    Here the denominator is destroyed with the source. There is no later
    count that could establish what was lost. A readout is not merely
    uncollected; it is unconstitutable.

Three states, not two, and the sub-case is the third:

    collectable        the denominator exists and nobody has counted it
    units-blocked      the denominator exists and does not share units
                       with the numerator            (GC_003, parent)
    unconstitutable    the denominator does not exist and cannot be made
                       to                            (SUBCASE 10A)

GC_003 stands and is now bounded: it is a statement about the parent
mechanism, where a denominator exists to have a units problem. It does not
transfer to the sub-case, and the sub-case does not rescue it.

The sub-case's own move is the stronger one and it is stated plainly --
do not measure the loss, measure the procedure. "Not the loss -- the loss
is unmeasurable by construction, and any tool claiming to quantify it is
producing a number where none exists." All three readouts are properties
of the record, and records exist.
""".strip())

# ------------------------------------------------------------------ GC_012
head(12, "GC_012", "S1, S2 and S3 have no fields in the scorer")
print()
for f in ("foreclosed", "reversibility", "non_destructive", "source_survives",
          "destructive", "ledger_check"):
    print("  %-18s appears in capacity.py: %s" % (f, f in open(
        os.path.join(HERE, "capacity.py"), encoding="utf-8").read()))
print()
print("""
capacity.py scores R1, R2 and R3 and has no slot for any of the three
sub-case readouts. The SKELETON emitted by `--new` carries `generations`,
`transmission_gap`, `loop` and `found_constraint_tests`; nothing there
holds a record-level three-valued answer.

That is the state the sub-case declares -- "No case in this file has
quantified readings. This is a schema, not a finding" -- and the same
shape as measurement-fork MF_017, category-weld CW_015 and domain-ledger
DL_004: a rule stated in prose with no schema slot to express it.

It is cheaper here than in any of those. S1 and S3 are three-valued
enumerations over a fixed vocabulary and S2 is a boolean with a named
negative branch; all three are properties of one record, so a sub-case
entry is flat and needs no generational structure. The distinguishing
work -- absent versus zero -- is already done in the specification.

The OPEN section also fixes its own boundary before classifying, which is
the third folder to state that discipline: "Whether the sub-case extends
to sources that are not objects ... the boundary has not been tested and
should be fixed before cases are classified, not after."
""".strip())


print()
print(BAR)
print("end of audit -- findings recorded in AUDIT_NOTES.md as GC_001..GC_012")
print(BAR)
