#!/usr/bin/env python3
"""mechanism_10_audit.py -- checks on MECHANISM 10, GENERATION CAPACITY REMOVED.

Added, not delivered. MECHANISM_10.md is the drop as received and is not
modified. Findings are recorded in AUDIT_NOTES.md as GC_001..GC_007.

    python3 mechanism_10_audit.py

The mechanism makes one claim that is directly checkable against an
instrument already in this repo: "a binary that passes an option-space
audit truthfully". ../presented-binary/binary_audit.py is an option-space
audit. Section 1 runs it.

Nothing here quantifies R1, R2 or R3. The drop says no case has readings
and this audit does not invent one.

stdlib only, deterministic. CC0.
"""

import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BAR = "=" * 70


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BA = _load("binary_audit", os.path.join(ROOT, "presented-binary", "binary_audit.py"))

# The nine mechanisms already in play: eight in uninstrumented/README.md
# plus category-weld's proposed ninth. Each with what it requires to exist,
# so distinctness is checked against structure rather than against a label.
NINE = [
    ("MODALITY", "apparatus is in a different channel from the quantity"),
    ("STORAGE", "medium cannot hold the shape of the quantity"),
    ("SCALAR DEMAND", "one quantity's variation over a domain flattened to a scalar"),
    ("BUDGET BOUNDARY", "a closed budget compared against an open one"),
    ("AUTHORED REFERENCE", "the reference is produced by the MEASURED party"),
    ("PROXY SUBSTITUTION", "a named target displaced by a named enforceable stand-in"),
    ("AUDIT ASYMMETRY", "the guard fires on one side of a comparison only"),
    ("SCORED AS WASTE", "a component enters the accounting as cost"),
    ("CATEGORY WELD", "two measurable quantities fused into one handle"),
]

# A framing under MECHANISM 10, answered honestly. Every answer is what the
# affected party would truthfully give: the options really were generated
# by them, the search really was widened, the constraint really does hold.
HONEST = {
    "case": "under-mechanism-10",
    "presented_as": "two options",
    "source": "constructed for this audit, not a documented incident",
    "checks": {
        "O1": {"state": "documented", "answer": "two",
               "record": "generation session minuted"},
        "O2": {"state": "documented", "answer": "three weeks",
               "record": "calendar"},
        "O3": {"state": "documented",
               "answer": "generated by the affected party; all inside the set",
               "record": "attendance list"},
        "O4": {"state": "documented", "answer": "attempt recorded, not only result",
               "record": "minutes"},
        "O5": {"state": "documented",
               "answer": "widened twice; returned nothing new",
               "record": "second and third session minutes"},
        "O6": {"state": "documented",
               "answer": "each constraint held under push; FOUND, not authored",
               "record": "transcript"},
        "S1": {"state": "documented", "answer": "selected by the affected party, inside it",
               "record": "vote record"},
        "S2": {"state": "documented", "answer": "counted by functional position",
               "record": "role inventory"},
        "S3": {"state": "documented", "answer": "no-sacrifice branch specified in advance",
               "record": "pre-registration"},
        "S4": {"state": "documented", "answer": "post-audit scheduled, owner named",
               "record": "schedule"},
        "S5": {"state": "documented", "answer": "wrong-call condition stated in advance",
               "record": "pre-registration"},
    },
}


def head(n, cid, title):
    print()
    print(BAR)
    print("%-2d %s  %s" % (n, cid, title))
    print(BAR)


print("generation-capacity -- audit of MECHANISM 10")
print("delivered: MECHANISM_10.md (marker under exploration)")
print("instrument borrowed for section 1: ../presented-binary/binary_audit.py")

# ------------------------------------------------------------------ GC_001
head(1, "GC_001", "the claim that a binary under this mechanism passes an audit")
print("""
MECHANISM_10.md, VISIBLE AS:

    A binary that passes an option-space audit truthfully. Two alternatives
    generated, because two is the ceiling of what the party's remaining
    knowledge can produce.

presented-binary/binary_audit.py is an option-space audit with eleven
checks. Answered honestly by a party under this mechanism -- every answer
true, every answer with a record behind it:
""".strip())
s = BA.score(HONEST)
print()
for cid, block, q in BA.CHECKS:
    e = HONEST["checks"][cid]
    print("  %-3s [%-10s] %s" % (cid, e["state"], e["answer"]))
print()
print("  documented %d   asserted %d   absent %d   documented_share %.3f" % (
    s["documented"], s["asserted"], s["absent"], s["documented_share"]))
print()
print("""
11 of 11 documented. The claim holds against the instrument as delivered.

O3 is the cell the mechanism is aimed at. It asks "who generated them, and
are they inside the affected set?" and it exists to catch options
generated by people who do not carry the consequences. Under MECHANISM 10
the options ARE generated by the affected party, so O3's answer is the one
that reassures -- and that answer is the mechanism's signature, not its
absence. O5 is the second: widening a search over a reduced generator
returns nothing new, which reads as confirmation that the set was
complete.

The mechanism understates its own case, though, and the understatement is
worth measuring. binary_audit computes no verdict; documented_share is the
share of checks with a RECORD behind them and never reads what the record
says. So the same eleven checks, answered damningly with full records:
""".strip())
ids = [c[0] for c in BA.CHECKS]
for label, ans in (("favourable", "reassuring on every check"),
                   ("damning", "outsiders decided, constraint converted to urgency")):
    c = {"case": label,
         "checks": {i: {"state": "documented", "answer": ans, "record": "r"}
                    for i in ids}}
    sc = BA.score(c)
    print("  %-12s documented %2d   documented_share %.3f" % (
        label, sc["documented"], sc["documented_share"]))
print()
print("""
Identical. The pass is over-determined: a framing under MECHANISM 10 does
not need its answers to come out favourable, because the instrument's only
number does not grade answers. VISIBLE AS claims the audit is passed on
the merits; it is passed before the merits are reached.

That is a joint reading, not two separate findings. binary_audit's own
docstring is explicit that it computes no verdict and reports how much of
the framing has a record behind it -- which is a deliberate and defensible
scope. The consequence is that "passes an option-space audit" is a weaker
statement than it sounds, and MECHANISM 10 would still pass an instrument
that DID grade answers, for the reason the mechanism gives.

Either way it is not a defect in any check. All eleven ask about the
decision episode, and the removal happened before it, on a clock the
answering party has no access to. An audit of the episode cannot reach it.
""".strip())

# ------------------------------------------------------------------ GC_002
head(2, "GC_002", "the check that is missing, and why it cannot be a twelfth")
print("""
The obvious repair is a twelfth check in the option_space block. It does
not work, and the drop says why:

    Therefore recall must be scored against what is PRESENT IN THE PLACE,
    never against what the center knows. Any implementation scoring
    against a central reference reproduces the mechanism it is measuring.

Every existing check resolves to documented / asserted / absent against
the answering party's own record. A twelfth check of the same type --
"was generation capacity intact?" -- would be scored against that same
record, which is the record of a party whose generator was reduced.
Absent generation capacity produces an absent record of it. The check
returns `absent` and reads as a gap in documentation.

So the readout cannot be a state in this vocabulary. R1 is a RATIO with an
external denominator, which is a different kind of instrument: it needs
what is present in the place, not what the party can say about itself.

That is a real structural point in the drop's favour, and it also means
binary_audit.py cannot be extended to cover MECHANISM 10 -- the mechanism
needs a second instrument beside it, not another row.
""".strip())

# ------------------------------------------------------------------ GC_003
head(3, "GC_003", "R1's two named denominators are not interchangeable")
print("""
    R1 -- recall ratio. Nameable / present, per place, per generation.
    Denominator from ethnobotanical and floristic inventories, which
    exist. Numerator from resident recall, which is not collected against
    them.

    ... it is a collection gap rather than a method gap.

The two named sources break in different places, and neither is the
denominator the ratio needs as stated.

  FLORISTIC inventory
    Linnaean, produced by the center, independent of resident recall --
    so it is a genuine independent denominator, which is what the ratio
    needs. But scoring resident recall against it requires mapping local
    names onto species: a resident naming one plant where the inventory
    splits three, or three where it lumps one. That mapping IS scoring
    against a central reference, which the CALIBRATION CONSTRAINT four
    paragraphs earlier forbids.

  ETHNOBOTANICAL inventory
    Collected from residents, so the mapping problem does not arise --
    the units already match. But it inherits the recall of whoever was
    surveyed when it was made. Measuring recall against it is measuring
    recall against earlier recall, which is R2 (transmission interval),
    not R1. It cannot supply an independent denominator because it is a
    numerator from a previous generation.

Stated as a fork: the independent denominator needs a translation step the
constraint forbids, and the translatable denominator is not independent.

This does not sink R1. It relocates the gap: part of what the drop files
under collection is a method question about what counts as one nameable
item, and it has to be settled before a numerator is collected, not after.
The drop's own constraint is what surfaces it.
""".strip("\n"))

# ------------------------------------------------------------------ GC_004
head(4, "GC_004", "R3's two outcomes are 'yes' and 'not found'")
print("""
    R3 -- loop check. Is the resulting deficit cited as grounds for the
    gate that produced it. Binary, evidenced by citation or absent.

Evidenced by citation, or absent. A citation that was never searched for
and a citation that does not exist both return absent. The negative
outcome is not reachable by the stated procedure -- there is no state that
means "looked, and the deficit is not cited".

null-harness grades this shape CONSTANT_SILENT on the negative branch: the
readout can confirm the loop and cannot disconfirm it.

The repair is the one R1 already has and R3 does not: a denominator. Name
the corpus searched -- which decision records, over which interval -- so
that zero citations in a named corpus is a measurement and zero citations
in no corpus is a gap. binary_audit.py's O4 already works this way -- it
asks whether a record of the generation attempt EXISTS, not what it says.

R1 and R2 are declared untested; R3 is declared specified. This is a
statement about the specification.
""".strip("\n"))

# ------------------------------------------------------------------ GC_005
head(5, "GC_005", "distinctness against the nine, by structure")
print()
for label, structure in NINE:
    print("  %-20s %s" % (label, structure))
print()
print("""
The two that get closest run in opposite directions and neither closes.

AUDIT ASYMMETRY is "the guard fires on one side of a comparison only". The
LOOP FORM is an asymmetry that becomes its own justification, which is
close -- but AUDIT ASYMMETRY is about a guard's behaviour at audit time,
and here there is no guard misfiring. The audit runs correctly on both
sides (section 1) and the asymmetry is upstream of it.

AUTHORED REFERENCE is "the reference is produced by the MEASURED party" --
a model authoring the benchmark it is scored on. The CALIBRATION
CONSTRAINT names the mirror image: the reference is produced by the party
whose gate created the deficit, and the measured party is the one scored
against it. Same defect in the reference, opposite direction of authorship.

That mirror is worth stating as its own line rather than folding into
either mechanism, because the remedies differ. AUTHORED REFERENCE is
repaired by an external fixed reference (anchor-interval ANC_005..008,
criteria-drift CD_008). This one is made WORSE by an external fixed
reference, if the external reference is the center's -- which is exactly
what the CALIBRATION CONSTRAINT says.

MECHANISM 10 is distinct on the check as written. What would fold it back
in: showing a case where the generator was reduced AND the reduction is
carried somewhere in the record, since then it is a suppression at
decision time and the drop's own EXCLUDED BY paragraph rules it out.
""".strip())

# ------------------------------------------------------------------ GC_006
head(6, "GC_006", "SELF-MAINTAINING is a rate claim and it is already modelled")
print("""
    Active restriction needs continuous expenditure; a removed generator
    needs none. The arrangement persists at zero maintenance cost, which
    is why it outlasts the conditions that produced it.

This is the strongest sentence in the drop, because it is a claim about
cost asymmetry rather than about anyone's conduct, and this repo already
has two instruments shaped for it.

  rigidification-sensor/simulator.py records per tick a `continuation`
  cost and a `reversal` cost, and reports `locked_at` -- the first tick
  where reversal exceeds continuation AND the derivative does too. Zero
  maintenance cost is continuation -> 0, which sends the ratio to the lock
  condition without anything being done. The folder states throughout that
  "control" means control PARAMETER, not a hand on a knob, which is the
  same "no intent required" the LOOP FORM states.

  sustained-activation-gate/ is a tilted double well: the system stays in
  a basin at zero drive, and getting out costs a Kramers escape. A removed
  generator is the well that needs no one holding the system in it.

Neither is a metaphor for the other -- they are the same rate comparison
in three vocabularies. What connects them concretely: R2 (transmission
interval) is the time axis those two simulators run on, and a measured R2
would give the lock check an interval instead of a tick index.

Recorded as an available instrument, not as a result. Nothing has been run.
""".strip("\n"))

# ------------------------------------------------------------------ GC_007
head(7, "GC_007", "the consent claim is the load-bearing one and is not measured")
print("""
    A party rendered unable to generate the alternative cannot consent
    against it. Consent is structurally unavailable while the framing
    still reads as a hard choice made responsibly. This is stronger than
    "the framing is unaudited": the audit's subject cannot be constituted.

Section 1 supports the second sentence as far as the instrument reaches:
the framing scores 11 of 11 documented, so "reads as a hard choice made
responsibly" is a number here rather than a characterisation. With the
qualification section 1 established -- that number grades record
completeness, not the merits of the answers, so what it establishes is
that the framing survives the audit intact, not that the audit approved
of it.

The first sentence is a different kind of claim. "Cannot consent against
an option it cannot generate" is close to analytic -- consent to forgo X
requires X to be available to consider -- and what makes it empirical is
the antecedent: WAS the party unable to generate it. That is R1, and R1
has no readings.

So the chain is: R1 (unmeasured) -> inability (unestablished) -> consent
unavailable (follows). The last step is the cheap one. The drop's own
CONFIDENCE section says as much, and this section records that the load
is concentrated entirely in R1's numerator rather than spread across the
three readouts.

The seed case is chosen well for this: edible species has an existing
denominator and a collectable numerator, and the collection is a survey,
not an experiment. What it does not have yet is GC_003's units decision.
""".strip("\n"))

print()
print(BAR)
print("end of audit -- findings recorded in AUDIT_NOTES.md as GC_001..GC_007")
print(BAR)
